<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <groupId>org.openprovenance.prov</groupId>
        <artifactId>modules-tools</artifactId>
        <version>${provtoolboxVersion}</version>
    </parent>


    <modelVersion>4.0.0</modelVersion>
    <artifactId>${rootArtifactId}-root</artifactId>
    <groupId>${groupId}</groupId>
    <name>|---- ${rootArtifactId}-root</name>
    <packaging>pom</packaging>
    <description>A project for Provenance Template Management</description>
    <version>${version}</version>

    <modules>

    </modules>




    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <pom.service.port>${servicePort}</pom.service.port>
        <pom.service.context>${serviceContext}</pom.service.context>
        <pom.service.host>localhost</pom.service.host>
        <pom.service.protocol>http</pom.service.protocol>
        <pom.the.template.library>${templateLibraryArtifactId}</pom.the.template.library>
        <pom.the.template.library.version>${templateLibraryVersion}</pom.the.template.library.version>
        <pom.the.template.sublibrary>${templateSubLibrary}</pom.the.template.sublibrary>
        <pom.templates.button.label>${templatesButtonLabel}</pom.templates.button.label>
        <pom.project.version>${project.version}</pom.project.version>
        <pom.catalogue.package>${cataloguePackage}</pom.catalogue.package>
        <pom.jdbc.url>${jdbcURL}</pom.jdbc.url>
        <pom.form.dashboard.title>${dashboardTitle}</pom.form.dashboard.title>
        <pom.logger.constructor>${loggerConstructor}</pom.logger.constructor>
        <unsecure.webxml.location>${project.basedir}/src/main/webapp.filter/WEB-INF/web-no-security.xml</unsecure.webxml.location>
        <secure.webxml.location>${project.basedir}/src/main/webapp.filter/WEB-INF/web-with-security.xml</secure.webxml.location>
        <lexicon.location>/Users/luc/IdeaProjects/ProvToolbox/modules-explanations/nlg-wrapper/target/dictionary/lexAccess2013.data</lexicon.location>
        <template.config.location>target/test-classes/template-config.json</template.config.location>
        <security.config.location>target/test-classes/security/openprovenance-auth2-security-config.json</security.config.location>
        <pom.nlg.xplan.library>${nlgXplanLibrary}</pom.nlg.xplan.library>
        <pom.nlg.xplan.selection>${nlgXplanSelection}</pom.nlg.xplan.selection>
        <pom.icons.folder.for.graphviz>${project.build.directory}/extracted-icons</pom.icons.folder.for.graphviz>
        <pom.the.icon.svg.library>${theIconSvgLibrary}</pom.the.icon.svg.library>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.5.0</version>
                    <configuration>
                        <propertiesEncoding>${project.build.sourceEncoding}</propertiesEncoding>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>




</project>
