version: "3.0"


services:

  provtranslator:
    env_file: env_file.env
    image: docker-service-translator.temurin
    restart: always
    ports:
      - "8080:8080"
    links:
      - redis:redis
      - mongo:mongo
    environment:
      - CATALINA_OPTS=-DPSERVICE_STORAGE=fs -DPSERVICE_REDIS_HOST=redis -DPSERVICE_REDIS_PORT=6379 -DPSERVICE_MONGO_HOST=mongo -DPSERVICE_MONGO_PORT=27017
    volumes:
      - $FILE_HOME:/home/pservice
    depends_on:
      - redis


  redis:
    env_file: env_file.env
    image: redis
    restart: always
    expose:
      - 6379
    volumes:
      - $REDIS_HOME:/data
    command: [redis-server, '--appendonly yes']

  mongo:
    env_file: env_file.env
    image: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - $MONGO_HOME:/data/db
