


t1:
	target/appassembler/bin/provconvert -asn2rdf ../asn/src/test/resources/prov/w3c-publication1.prov-asn target/w3c-publication1.ttl
	target/appassembler/bin/provconvert -asn2xml ../asn/src/test/resources/prov/w3c-publication1.prov-asn target/w3c-publication1.xml


t2:
	target/appassembler/bin/provconvert -asn2rdf ../asn/src/test/resources/prov/w3c-publication2.prov-asn target/w3c-publication2.ttl
	target/appassembler/bin/provconvert -asn2xml ../asn/src/test/resources/prov/w3c-publication2.prov-asn target/w3c-publication2.xml

t3:
	target/appassembler/bin/provconvert -asn2rdf ../asn/src/test/resources/prov/w3c-publication3.prov-asn target/w3c-publication3.ttl
	target/appassembler/bin/provconvert -asn2xml ../asn/src/test/resources/prov/w3c-publication3.prov-asn target/w3c-publication3.xml




# provide absolute arguments
note:
	target/appassembler/bin/provconvert -asn2rdf `pwd`/../asn/src/test/resources/prov/w3c-publication1.prov-asn `pwd`/target/w3c-publication1.ttl

