

run:
	mkdir -p target/foo
	cd target/foo; mvn archetype:generate -DgroupId=org.example -DartifactId=demo -Dversion=0.1-SNAPSHOT -DarchetypeGroupId=org.openprovenance.prov -DarchetypeArtifactId=prov-template-archetype
	ls -lR target/foo