HERE=/home/lavm/papers/papers/prov-wg/git/ProvToolbox/asn
HERE=/Users/lavm/luc-svn/papers/prov-wg/git/ProvToolbox/asn

go:
	sh target/appassembler/bin/asn $(HERE)/src/test/resources/prov/container0.prov 
	sh target/appassembler/bin/asn $(HERE)/src/test/resources/prov/container1.prov 
	sh target/appassembler/bin/asn $(HERE)/src/test/resources/prov/container2.prov 
	cat $(HERE)/src/test/resources/prov/container2.prov.xml


