HERE=/home/lavm/papers/papers/prov-wg/git/ProvToolbox/asn
HERE=/Users/lavm/luc-svn/papers/prov-wg/git/ProvToolbox/asn
go:
	sh target/appassembler/bin/asn $(HERE)/src/test/resources/prov/container0.prov 
	sh target/appassembler/bin/asn $(HERE)/src/test/resources/prov/container1.prov 
	sh target/appassembler/bin/asn $(HERE)/src/test/resources/prov/container2.prov 
	cat $(HERE)/src/test/resources/prov/container2.prov.xml


go3:
	sh target/appassembler/bin/asn $(HERE)/src/test/resources/prov/container3.prov 



p2:
	sh target/appassembler/bin/asn $(HERE)/src/test/resources/prov/file-example2.asn
	cat $(HERE)/src/test/resources/prov/file-example2.asn.xml

p1:
	sh target/appassembler/bin/asn $(HERE)/src/test/resources/prov/file-example1.asn
	cat $(HERE)/src/test/resources/prov/file-example1.asn.xml


p3:
	sh target/appassembler/bin/asn $(HERE)/src/test/resources/prov/file-example3.asn
	cat $(HERE)/src/test/resources/prov/file-example3.asn.xml



