go:
	sh target/appassembler/bin/asn src/test/resources/prov/container0.prov 
	sh target/appassembler/bin/asn src/test/resources/prov/container1.prov 
	sh target/appassembler/bin/asn src/test/resources/prov/container2.prov 

