package org.openprovenance.prov.template.compiler.integration;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;
import org.openprovenance.prov.template.compiler.CompilerSimpleBean;
import org.openprovenance.prov.template.compiler.CompilerUtil;
import org.openprovenance.prov.template.compiler.common.BeanKind;
import org.openprovenance.prov.template.compiler.common.CompilerCommon;
import org.openprovenance.prov.template.compiler.configuration.SimpleTemplateCompilerConfig;
import org.openprovenance.prov.template.descriptors.TemplateBindingsSchema;

import javax.lang.model.element.Modifier;
import java.util.List;


public class CompilerIntegrator {
    private final CompilerCommon compilerCommon;
    private final CompilerUtil compilerUtil = new CompilerUtil();
    private final boolean debugComment = true;

    public CompilerIntegrator(CompilerCommon compilerCommon) {
        this.compilerCommon = compilerCommon;

    }

    public JavaFile generateIntegrator(String templateName, String packge, TemplateBindingsSchema bindingsSchema) {

        TypeSpec.Builder builder = compilerUtil.generateClassInit(compilerUtil.integratorBuilderNameClass(templateName));


        builder.addMethod(compilerCommon.generateProcessorConverter(templateName, packge, bindingsSchema, BeanKind.OUTPUTS));

        builder.addMethod(compilerCommon.generateNameAccessor(templateName));

        builder.addMethod(generateNewOutputConstructor(templateName, packge, bindingsSchema, BeanKind.OUTPUTS));

        TypeSpec spec = builder.build();

        return compilerUtil.specWithComment(spec, templateName, packge, getClass().getName());
    }

    public MethodSpec generateNewOutputConstructor(String templateName, String packge, TemplateBindingsSchema bindingsSchema, BeanKind outputs) {
        MethodSpec.Builder builder = MethodSpec.methodBuilder("newOutput")
                .addModifiers(Modifier.PUBLIC)
                .returns(ClassName.get(packge, compilerUtil.outputsNameClass(templateName)));
        if (debugComment)
            builder.addComment("Generated by method $N", getClass().getName() + ".generateNewOutputConstructor()");
        //builder.addTypeVariable(typeOutput);
        builder.addStatement("return new $N()", compilerUtil.outputsNameClass(templateName));


        return builder.build();

    }

    public JavaFile generateCompositeBean(String templateName, String consistOf, String packge, TemplateBindingsSchema bindingsSchema, List<String> sharing) {

        if (sharing != null && !sharing.isEmpty()) {
            String compositeBeanNameClass = compilerUtil.beanNameClass(templateName);
            //TypeSpec.Builder builder = compilerUtil.generateClassInit(compositeBeanNameClass);


            SimpleTemplateCompilerConfig config = new SimpleTemplateCompilerConfig();
            config.name = compositeBeanNameClass;
            config.package_ = packge;
            config.bindings = "openprovenance:composite-bean.json";
            config.template = "src/test/resources/templates/composite-bean.provn";

            TemplateBindingsSchema bindingsSchema2 = compilerUtil.getBindingsSchema(config);

            JavaFile myfile = new CompilerSimpleBean().generateSimpleBean(templateName, packge, bindingsSchema2, BeanKind.COMPOSITE, consistOf);


            return myfile;

        } else return null;
    }
}
