/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_native_embedding_CallbackTrampoline */

#ifndef _Included_org_example_native_embedding_CallbackTrampoline
#define _Included_org_example_native_embedding_CallbackTrampoline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_native_embedding_CallbackTrampoline
 * Method:    jumpToCallback
 * Signature: (JLorg/graalvm/polyglot/Value;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_example_native_1embedding_CallbackTrampoline_jumpToCallback
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
