package org.openprovenance.prov.template.compiler.past.emitter.registry;

/**
 * Broad category of a PAST/Java type, from the Rust emitter's perspective.
 *
 * <p>Used as the primary key for type-based dispatch decisions: HashMap vs Vec,
 * primitive Copy semantics, trait storage, string ownership conversions, etc.</p>
 *
 * <p>See {@link RustMethodRegistry#isCategory(org.openprovenance.prov.template.compiler.past.type.TypeName, RustTypeCategory)}
 * for the look-up API that replaces the scattered {@code isMap()}, {@code isList()},
 * {@code isPrimitiveType()} … boolean helpers in {@code Rust.java}.</p>
 */
public enum RustTypeCategory {

    /** {@code HashMap<K,V>} — key/value operations; key arguments need {@code &} and Option-unwrapping. */
    MAP,

    /** {@code Vec<T>} — ordered collection; {@code push} takes ownership. */
    LIST,

    /** {@code String} / {@code &str} — string type; may need {@code .to_string()} for owned conversion. */
    STRING,

    /** {@code i32}, {@code i64}, {@code bool}, {@code f64}, … — {@code Copy} types; no {@code .clone()} needed. */
    PRIMITIVE,

    /** {@code ()} — unit return type mapping to Java {@code void}/{@code Void}. */
    VOID,

    /** Functional interface / closure type (Java {@code Function<T,R>} and friends). */
    FUNCTION,

    /** Java {@code Class<T>} meta-type — emitted as {@code &'static str} in Rust. */
    CLASS_REF,

    /** {@code java.lang.Object} — emitted as {@code Box<dyn std::any::Any>}. */
    OBJECT,

    /** A known PAST interface — stored as {@code Option<Box<dyn Trait>>} in struct fields. */
    TRAIT,

    /** A user-defined struct generated by the template compiler. */
    STRUCT,

    /** Catch-all for types that do not receive any special Rust-emission treatment. */
    OTHER
}
