//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.10 at 05:05:05 PM GMT 
//


package org.openprovenance.prov.validation.report;

import org.openprovenance.apache.commons.lang.builder.EqualsBuilder;
import org.openprovenance.apache.commons.lang.builder.HashCodeBuilder;
import org.openprovenance.apache.commons.lang.builder.ToStringBuilder;
import org.openprovenance.prov.model.Statement;
import org.openprovenance.apache.commons.lang.builder.Equals;
import org.openprovenance.apache.commons.lang.builder.HashCode;
import org.openprovenance.apache.commons.lang.builder.ToString;

import jakarta.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for MalformedStatements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MalformedStatements"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded"&gt;
 *         &lt;group ref="{http://www.w3.org/ns/prov#}documentElements"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MalformedStatements", propOrder = {
    "entityAndActivityAndWasGeneratedBy"
})
public class MalformedStatements
    implements Equals, HashCode, ToString
{


    protected List<Statement> entityAndActivityAndWasGeneratedBy;

    /**
     * Gets the value of the entityAndActivityAndWasGeneratedBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityAndActivityAndWasGeneratedBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityAndActivityAndWasGeneratedBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     *
     * @return list of statements

     */
    public List<Statement> getStatement() {
        if (entityAndActivityAndWasGeneratedBy == null) {
            entityAndActivityAndWasGeneratedBy = new ArrayList<Statement>();
        }
        return this.entityAndActivityAndWasGeneratedBy;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof MalformedStatements)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final MalformedStatements that = ((MalformedStatements) object);
        equalsBuilder.append(this.getStatement(), that.getStatement());
    }

    public boolean equals(Object object) {
        if (!(object instanceof MalformedStatements)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new EqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getStatement());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new HashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

    public void toString(ToStringBuilder toStringBuilder) {
        {
            List<Statement> theEntityAndActivityAndWasGeneratedBy;
            theEntityAndActivityAndWasGeneratedBy = this.getStatement();
            toStringBuilder.append("entityAndActivityAndWasGeneratedBy", theEntityAndActivityAndWasGeneratedBy);
        }
    }

    public String toString() {
        final ToStringBuilder toStringBuilder = new ToStringBuilder(this);
        toString(toStringBuilder);
        return toStringBuilder.toString();
    }

}
