//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 11:38:35 AM BST 
//


package org.openprovenance.prov.xml;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.openprovenance.prov.model.DOMProcessing;


/**
 * <p>
 * Java class for Value complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Value">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anySimpleType">
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Value", namespace = "http://www.w3.org/ns/prov#")
public class Value extends TypedValue implements Equals, HashCode, ToString,
	org.openprovenance.prov.model.Value,

	org.openprovenance.prov.model.Attribute {

    private static final AttributeKind PROV_VALUE_KIND = org.openprovenance.prov.model.Attribute.AttributeKind.PROV_VALUE;
    private static final QName PROV_VALUE_QNAME = Helper.PROV_VALUE_QNAME;

    @Override
    public QName getElementName() {
	return PROV_VALUE_QNAME;
    }

    @Override
    public AttributeKind getKind() {
	return PROV_VALUE_KIND;
    }

    @Override
    public String toNotationString() {
	return DOMProcessing.qnameToString(getElementName()) + " = "
		+ Helper.valueToNotationString(getValue(), getType());
    }

}
   
 