//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.05 at 11:52:42 PM GMT 
//


package org.openprovenance.prov.model;

import java.net.URI;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class URIAdapter
    extends XmlAdapter<String, URI>
{


    public URI unmarshal(String value) {
        return (java.net.URI.create(value));
    }

    public String marshal(URI value) {
        return (ProvFactory.printURI(value));
    }

}
