package org.openprovenance.prov.model;

/**
 * <p>Java interface for the PROV Communication association.
 * 
 * <p><a href="http://www.w3.org/TR/prov-dm/#concept-communication">PROV-DM Definition for Communication</a>: 
 * Communication is the exchange of some unspecified entity by two activities, one activity using some entity 
 * generated by the other.
 *  
 *  <p>
 *  
 * @author lavm
 *
 */

public interface WasInformedBy extends Identifiable,  HasLabel, HasType, HasOther, Influence {

    void setInformed(QualifiedName pid1);

    void setInformant(QualifiedName pid2);

    QualifiedName getInformed();

    QualifiedName getInformant();

}
