//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.28 at 09:53:50 PM GMT 
//


package org.openprovenance.prov.sql;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.openprovenance.prov.model.DOMProcessing;
import org.openprovenance.prov.model.OtherAttribute;
import javax.xml.namespace.QName;


/**
 * <p>Java class for Other complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Other">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/ns/prov#>TypedValue">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Other")
@Entity(name = "Other")
@Table(name = "OTHER")
public class Other
    extends TypedValue
    implements Equals, HashCode, OtherAttribute, org.openprovenance.prov.model.Attribute
{

    QName elementName;

    @Transient
    public QName getElementName() {
	return elementName;
    }
    
    public void setElementName(QName elementName) {
	this.elementName=elementName;
    }

    @Basic
    @Column(name = "ELEMENTNAME") 
    public String getElementNameItem() {
	if (elementName==null) return null;
	return Helper2.QNameToString(elementName);
    }

    public void setElementNameItem(String name) {
	//System.out.println("---> setElementNameItem() reading " + name);
	elementName=Helper2.stringToQName(name);
	//System.out.println(" ---> setElementNameItem() got " + elementName);
    }

    
    private static final AttributeKind OTHER_KIND = org.openprovenance.prov.model.Attribute.AttributeKind.OTHER;
    

    @Transient    
    public AttributeKind getKind() {
	return OTHER_KIND;
    }

    public String toNotationString() {
        return DOMProcessing.qnameToString(getElementName()) + " = " + org.openprovenance.prov.xml.Helper.valueToNotationString(getValue(), getType());
    }



    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Other)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
