//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.14 at 10:55:43 PM GMT 
//

@javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter(AnyAdapter.class)@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/ns/prov#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openprovenance.prov.sql;
