package org.openprovenance.prov.template.compiler.past.emitter;

import org.openprovenance.prov.template.compiler.past.*;
import org.openprovenance.prov.template.compiler.past.Class;
import org.openprovenance.prov.template.compiler.past.Iterator;
import org.openprovenance.prov.template.compiler.past.annotations.OverloadedMethod;
import org.openprovenance.prov.template.compiler.past.annotations.PastAnnotation;
import org.openprovenance.prov.template.compiler.past.annotations.StaticMethod;
import org.openprovenance.prov.template.compiler.past.checker.ClassSignature;
import org.openprovenance.prov.template.compiler.past.checker.MethodSignature;
import org.openprovenance.prov.template.compiler.past.checker.TypeRegistry;
import org.openprovenance.prov.template.compiler.past.type.ArrayType;
import org.openprovenance.prov.template.compiler.past.type.ClassName;
import org.openprovenance.prov.template.compiler.past.type.ParameterizedType;
import org.openprovenance.prov.template.compiler.past.type.TypeName;
import org.openprovenance.prov.template.compiler.past.type.TypeVariable;

import java.io.File;
import java.io.IOException;
import javax.lang.model.element.Modifier;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.stream.Collectors;

import static org.openprovenance.prov.template.compiler.common.Constants.GENERATED_VAR_PREFIX;
import static org.openprovenance.prov.template.compiler.common.Constants.LOGGER;
import static org.openprovenance.prov.template.compiler.past.BinaryOp.INSTANCEOF;
import static org.openprovenance.prov.template.compiler.past.MethodCall.MethodCallKind.FUNCTIONAL_INTERFACE_CALL;
import static org.openprovenance.prov.template.compiler.past.MethodCall.MethodCallKind.SUPER_METHOD_CALL;

/**
 * Emitter that generates JavaScript class definitions from PAST abstract syntax tree.
 * Generates modern ES6+ JavaScript with classes, arrow functions, and native collections.
 */
public class JavaScript implements Emitter<StringBuilder> {
    private final TypeRegistry typeRegistry;
    private String currentPackageName;
    private ClassSignature currentClassSignature;
    private StringBuilder sb;
    private static final String INDENT = "  ";
    private int lambdaCount = 0;
    private Set<String> imports;
    private List<Method> lateMethods = new ArrayList<>();
    private Class currentClass;
    private String postDecrement = null;

    public JavaScript() {
        this.typeRegistry = null;
    }

    public JavaScript(TypeRegistry typeRegistry) {
        this.typeRegistry = typeRegistry;
    }

    public StringBuilder addHeader(StringBuilder sb, String templateName, String packge, StackTraceElement stackTraceElement) {
        sb.insert(0, "// Generated by ProvToolbox for template configuration '" + templateName + "'\n"
                + "// by class " + stackTraceElement.getClassName() + ", method " + stackTraceElement.getMethodName() +
                ",\n// in file " + stackTraceElement.getFileName() + ", at line " + stackTraceElement.getLineNumber() + "\n\n");
        return sb;
    }

    public WritableObject toWritableObject(Class clazz, String className, String packge, StackTraceElement stackTraceElement) {
        this.currentPackageName = packge;
        StringBuilder theBuffer = emit(clazz);

        addHeader(theBuffer, className, packge, stackTraceElement);
        return new WritableObject() {
            @Override
            public void writeTo(File directory) throws IOException {
                Path destination = Paths.get(directory.getAbsolutePath()).resolve(packge.replace('.', '/'));
                destination.toFile().mkdirs();
                java.nio.file.Path path = destination.resolve(clazz.name + ".js");
                java.nio.file.Files.writeString(path, theBuffer.toString());
            }
        };
    }

    @Override
    public StringBuilder emit(Class clazz) {
        StringBuilder sb = new StringBuilder();
        return emit(clazz, sb);
    }

    public StringBuilder emit(Class clazz, StringBuilder sb) {
        this.imports = new HashSet<>();
        this.lateMethods = new ArrayList<>();
        this.lambdaCount = 0;
        this.currentClass = clazz;
        this.currentClassSignature = (typeRegistry != null && currentPackageName != null)
                ? typeRegistry.lookup(clazz.name, currentPackageName) : null;

        // Class JSDoc comment
        if (!clazz.comments.isEmpty()) {
            sb.append("/**\n");
            for (Comment comment : clazz.comments) {
                List<String> lines = convert(comment);
                for (String line : lines) {
                    sb.append(" * ").append(line).append("\n");
                }
            }
            sb.append(" */\n");
        }

        // Class declaration
        sb.append("class ");
        if (clazz.name!=null) { // don't do it for anonymous classes
            sb.append(clazz.name);
        }

        if (clazz.superclass!=null) {
            sb.append(" extends ");
            if (clazz.superclass instanceof ParameterizedType) {
                ParameterizedType pt = (ParameterizedType) clazz.superclass;
                System.out.println("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ extends " + pt + " " + typeSimpleName(pt.rawType));
                sb.append(importAndGetLocalName(convert(pt.rawType)));
            } else {
                sb.append(importAndGetLocalName(sanitizeName(convert(clazz.superclass))));
            }
        }

        // Base classes - JavaScript only supports single inheritance
        // For now, we'll skip interfaces as they're not directly supported in JS

        sb.append(" {\n");

        // Constructor
        if (clazz.constructors.isEmpty()) {
            emitDefaultConstructor(clazz.fields, sb);
        } else {
            for (Constructor constructor : clazz.constructors) {
                emitConstructor(constructor, sb);
            }
        }

        // Methods
        if (!clazz.methods.isEmpty()) {
            for (Method method : clazz.methods) {
                emitMethod(method, sb);
            }
        }

        // Late methods (from lambda conversions)
        for (Method method : lateMethods) {
            emitMethod(method, sb);
        }

        // Static fields
        emitStaticFields(clazz.fields, sb);

        sb.append("}\n\n");

        if (clazz.name!=null) {
            // Export the class
            sb.append("module.exports = { ").append(clazz.name).append(" };\n");
        }

        // Add requires at the beginning
        if (!imports.isEmpty()) {
            StringBuilder importSection = new StringBuilder();
            for (String imprt : imports) {
                if (!imprt.contains(".")) continue;
                String localName = getLocalName(imprt);
                if (LOGGER.equals(localName)) continue;
                if (imprt.startsWith("past.util")) {
                    importSection.append("const ").append(localName).append(" = ").append(imprt).append(";\n");
                } else if (imprt.startsWith("past.exception")) {
                    importSection.append("const ").append(localName).append(" = ").append(imprt).append(";\n");
                } else if (imprt.startsWith("past.lang")) {
                    // ignore
                }
                else {

                    // Convert package path to  require path (was relative to ./ ; now not specified)
                    String importPath = imprt.replace('.', '/');
                    importSection.append("const { ").append(localName).append(" } = require('").append(importPath).append(".js');\n");
                }
            }
            if (importSection.length() > 0) {
                importSection.append("\n");
                sb.insert(0, importSection.toString());
            }
        }

        return sb;
    }

    private void emitDefaultConstructor(List<Field> fields, StringBuilder sb) {
        sb.append(INDENT).append("constructor(");

        // Parameters from non-static fields
        List<Field> instanceFields = fields.stream()
                .filter(f -> !f.modifiers.contains(Modifier.STATIC))
                .collect(Collectors.toList());

        for (int i = 0; i < instanceFields.size(); i++) {
            Field field = instanceFields.get(i);
            if (i > 0) sb.append(", ");
            sb.append(sanitizeName(field.name));
            if (field.initialiser != null || !hasRequiredInitializer(field)) {
                sb.append(" = null");
            }
        }
        sb.append(") {\n");

        // Field assignments
        for (Field field : fields) {
            if (!field.modifiers.contains(Modifier.STATIC)) {
                String fieldName = sanitizeName(field.name);
                sb.append(INDENT).append(INDENT)
                        .append("this.").append(fieldName).append(" = ");
                if (field.initialiser != null) {
                    sb.append(convert(field.initialiser));
                } else {
                    sb.append(fieldName);
                }
                sb.append(";\n");
            }
        }

        sb.append(INDENT).append("}\n\n");


        // Add toJSON method
        //sb.append(INDENT).append("toJSON() {\n");
        //sb.append(INDENT).append(INDENT).append("return JSON.stringify(this, null, 2);\n");
        //sb.append(INDENT).append("}\n\n");
    }

    private void emitConstructor(Constructor constructor, StringBuilder sb) {
        sb.append(INDENT).append("constructor(");

        // Parameters
        if (constructor.parameters != null) {
            for (int i = 0; i < constructor.parameters.size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append(sanitizeName(constructor.parameters.get(i).name));
            }
        }
        sb.append(") {\n");

        // Constructor body
        for (Statement statement : constructor.body) {
            emitStatement(statement, INDENT + INDENT, sb);
        }

        sb.append(INDENT).append("}\n\n");
    }

    private void emitStaticFields(List<Field> fields, StringBuilder sb) {
        for (Field field : fields) {
            if (field.modifiers.contains(Modifier.STATIC)) {
                String fieldName = sanitizeName(field.name);
                sb.append("\nstatic ").append(fieldName)
                        .append(" = ");
                if (field.initialiser != null) {
                    sb.append(convert(field.initialiser));
                } else {
                    sb.append("null");
                }
                sb.append(";\n");
            }
        }
    }

    private void emitMethod(Method method, StringBuilder sb) {
        // JSDoc comment
        if (method.comments != null && !method.comments.isEmpty()) {
            sb.append(INDENT).append("/**\n");
            for (Comment comment : method.comments) {
                List<String> lines = convert(comment);
                for (String line : lines) {
                    sb.append(INDENT).append(" * ").append(line).append("\n");
                }
            }
            sb.append(INDENT).append(" */\n");
        }

        // Static modifier
        if (method.modifiers.contains(Modifier.STATIC)) {
            sb.append(INDENT).append("static ");
        } else {
            sb.append(INDENT);
        }

        // Method signature – use registry alt name for overloaded methods
        String altName = findAltNameForDeclaration(method);
        String methodName = (altName != null) ? altName : method.name;
        sb.append(sanitizeName(methodName)).append("(");

        // Parameters
        if (method.parameters != null) {
            for (int i = 0; i < method.parameters.size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append(sanitizeName(method.parameters.get(i).name));
            }
        }
        sb.append(") {\n");

        // Method body
        if (method.body != null && !method.body.isEmpty()) {
            for (Statement statement : method.body) {
                emitStatement(statement, INDENT + INDENT, sb);
            }
        }

        sb.append(INDENT).append("}\n\n");
    }


    private void emitStatement(Statement statement, String indent, StringBuilder sb) {

        switch (statement.statementKind) {
            case ASSIGNMENT -> {
                Assignment assignment = (Assignment) statement;

                // Handle import annotations
                if (false && !assignment.annotation.isEmpty()) {
                    for (String annot : assignment.annotation) {
                        if (annot.startsWith("@import")) {
                            String importString = annot.substring(7).trim();
                            delayedImport(sb, indent, importString);
                        }
                    }
                }

                if (assignment.leftHandExpression instanceof Variable
                        && ((Variable) assignment.leftHandExpression).name.equals("this")) {
                    return;
                }

                sb.append(indent);

                sb.append(sanitizeName(convertLH(assignment.leftHandExpression)))
                        .append(" = ")
                        .append(convert(assignment.value))
                        .append(";\n");

                if (postDecrement != null) {
                    sb.append(indent)
                            .append(postDecrement)
                            .append("--;\n");
                    postDecrement = null;
                }
            }

            case DEFINITION -> {
                Definition definition = (Definition) statement;

                // Handle import annotations
                if (false && !definition.annotation.isEmpty()) {
                    for (String annot : definition.annotation) {
                        if (annot.startsWith("@import")) {
                            String importString = annot.substring(7).trim();
                            delayedImport(sb, indent, importString);
                        }
                    }
                }

                if (definition.leftHandExpression instanceof Variable
                        && ((Variable) definition.leftHandExpression).name.equals("this")) {
                    return;
                }

                sb.append(indent);

                // Add const/let for new variables
                if (definition.type != null && definition.leftHandExpression instanceof Variable) {
                    if (definition.modifiers.contains(Modifier.FINAL)) {
                        sb.append("const ");
                    } else {
                        sb.append("let ");
                    }
                }

                sb.append(sanitizeName(convertLH(definition.leftHandExpression)))
                        .append(" = ")
                        .append(convert(definition.value))
                        .append(";\n");

                if (postDecrement != null) {
                    sb.append(indent)
                            .append(postDecrement)
                            .append("--;\n");
                    postDecrement = null;
                }
            }

            case RETURN -> {
                Return ret = (Return) statement;
                sb.append(indent)
                        .append("return ")
                        .append(convert(ret.expression))
                        .append(";\n");
            }

            case COMMENT -> {
                Comment cs = (Comment) statement;
                List<String> lines = convert(cs);
                for (String line : lines) {
                    sb.append(indent)
                            .append("// ")
                            .append(line)
                            .append("\n");
                }
            }

            case EXPRESSION_STATEMENT -> {
                Expression es = (Expression) statement;
                sb.append(indent)
                        .append(convert(es))
                        .append(";\n");
            }

            case IF_STATEMENT -> {
                IfStatement ifs = (IfStatement) statement;
                sb.append(indent)
                        .append("if (")
                        .append(convert(ifs.condition))
                        .append(") {\n");
                if (ifs.thenBlock.isEmpty()) {
                    sb.append(indent).append(INDENT).append("// empty\n");
                } else {
                    for (Statement thenStmt : ifs.thenBlock) {
                        emitStatement(thenStmt, indent + INDENT, sb);
                    }
                }
                if (!ifs.elseBlock.isEmpty()) {
                    sb.append(indent)
                            .append("} else {\n");
                    for (Statement elseStmt : ifs.elseBlock) {
                        emitStatement(elseStmt, indent + INDENT, sb);
                    }
                }
                sb.append(indent).append("}\n");
            }

            case FOR_LOOP -> {
                ForLoop forLoop = (ForLoop) statement;
                Statement initialization = forLoop.initialization;
                Expression condition = forLoop.condition;
                Statement update = forLoop.update;

                sb.append(indent)
                        .append("for (");

                // Inline the initialization, condition, and update
                String initStr = convertStatementInline(initialization);
                sb.append(initStr).append("; ");
                sb.append(convert(condition)).append("; ");
                String updateStr = convertStatementInline(update);
                sb.append(updateStr);

                sb.append(") {\n");
                for (Statement bodyStmt : forLoop.body) {
                    emitStatement(bodyStmt, indent + INDENT, sb);
                }
                sb.append(indent).append("}\n");
            }

            case ITERATOR -> {
                Iterator iterator = (Iterator) statement;
                sb.append(indent)
                        .append("for (const ")
                        .append(sanitizeName(iterator.parameter.name))
                        .append(" of ")
                        .append(convert(iterator.collection))
                        .append(") {\n");
                for (Statement bodyStmt : iterator.body) {
                    emitStatement(bodyStmt, indent + INDENT, sb);
                }
                sb.append(indent).append("}\n");
            }

            case THROW -> {
                ThrowStatement throwStmt = (ThrowStatement) statement;
                sb.append(indent)
                        .append("throw ")
                        .append(convert(throwStmt.expression))
                        .append(";\n");


            }

            case DO_LOOP -> {
                DoLoop doLoop = (DoLoop) statement;
                sb.append(indent)
                        .append("do {\n");

                for (Statement bodyStmt : doLoop.body) {
                    emitStatement(bodyStmt, indent + INDENT, sb);
                }
                sb.append(indent).append("}\n");
                sb.append(indent).append(" while (\n");
                        sb.append(convert(doLoop.condition))
                        .append(");\n");


            }



            default -> {
                System.out.println("Unsupported statement type: " + statement);
                throw new IllegalArgumentException("Unsupported statement type " + statement);
            }
        }
    }

    private String convertStatementInline(Statement statement) {
        switch (statement.statementKind) {
            case ASSIGNMENT -> {
                Assignment assignment = (Assignment) statement;
                StringBuilder result = new StringBuilder();
                result.append(sanitizeName(convertLH(assignment.leftHandExpression)))
                        .append(" = ")
                        .append(convert(assignment.value));
                return result.toString();
            }
            case DEFINITION -> {
                Definition definition = (Definition) statement;
                StringBuilder result = new StringBuilder();
                if (definition.leftHandExpression instanceof Variable) {
                    result.append("let ");
                }
                result.append(sanitizeName(convertLH(definition.leftHandExpression)))
                        .append(" = ")
                        .append(convert(definition.value));
                return result.toString();
            }
            case EXPRESSION_STATEMENT -> {
                Expression es = (Expression) statement;
                return convert(es);
            }
            default -> {
                System.out.println("Cannot inline statement type: " + statement);
                throw new IllegalArgumentException("Cannot inline statement type " + statement.statementKind);
            }
        }
    }

    private String convertStatementForLambda(Statement statement, String indent) {
        StringBuilder sb = new StringBuilder();
        switch (statement.statementKind) {
            case ASSIGNMENT -> {
                Assignment assignment = (Assignment) statement;
                sb.append(indent)
                        .append(sanitizeName(convertLH(assignment.leftHandExpression)))
                        .append(" = ")
                        .append(convert(assignment.value));
            }
            case EXPRESSION_STATEMENT -> {
                Expression es = (Expression) statement;
                switch (es.expressionKind) {
                    case METHOD_CALL -> {
                        MethodCall mc = (MethodCall) es;
                        sb.append(indent).append(convertMethodCall(mc));
                    }
                    case ARRAY_INITIALISER -> {
                        ArrayInitialiser ai = (ArrayInitialiser) statement;
                        sb.append(indent).append(convert(ai));
                    }
                    default -> {
                        throw new UnsupportedOperationException("Lambda body restriction: Unsupported EXPRESSION_STATEMENT kind " + es.expressionKind);
                    }
                }
            }
            case RETURN -> {
                Return ret = (Return) statement;
                sb.append(indent).append(convert(ret.expression));
            }
            default -> {
                System.out.println("Unsupported statement type in lambda: " + statement);
                throw new IllegalArgumentException("Unsupported statement type in lambda " + statement);
            }
        }
        return sb.toString();
    }

    private String convert(Expression expression) {
        switch (expression.expressionKind) {
            case VARIABLE: {
                Variable ve = (Variable) expression;
                return switch (ve.field) {
                    case STATIC_FIELD_VARIABLE -> currentClass.name + "." + sanitizeName(ve.name);
                    case FIELD_VARIABLE -> "this." + sanitizeName(ve.name);
                    case LOCAL_VARIABLE -> convertVariableName(sanitizeName(ve.name));
                };
            }

            case CONSTANT: {
                Constant constant = (Constant) expression;
                return convertConstant(constant);
            }

            case METHOD_CALL: {
                MethodCall mc = (MethodCall) expression;
                return convertMethodCall(mc);
            }

            case ARRAY_INITIALISER: {
                ArrayInitialiser ai = (ArrayInitialiser) expression;
                return "[" + ai.values.stream()
                        .map(this::convert)
                        .collect(Collectors.joining(", ")) + "]";
            }

            case CAST: {
                CastExpression c = (CastExpression) expression;
                // JavaScript doesn't have type casting, just return the expression
                return convert(c.expression);
            }

            case LAMBDA_EXPRESSION: {
                LambdaExpression le = (LambdaExpression) expression;

                // If multi-statement lambda, extract to separate method
                if (le.body.size() != 1 || !isSimpleLambdaBody(le.body.get(0))) {
                    String funName = "lambda" + (lambdaCount++);
                    Method method = new Method(funName);
                    method.parameters.addAll(le.parameters.stream()
                            .map(p -> new Parameter(sanitizeName(p.name), p.type))
                            .collect(Collectors.toList()));
                    method.body.addAll(le.body);

                    lateEmitMethod(method);

                    // Return reference to the method
                    return "this." + funName + ".bind(this)";
                }

                // Simple arrow function
                StringBuilder result = new StringBuilder();
                if (le.parameters.size() == 1) {
                    result.append(sanitizeName(le.parameters.get(0).name));
                } else {
                    result.append("(");
                    result.append(le.parameters.stream()
                            .map(p -> sanitizeName(p.name))
                            .collect(Collectors.joining(", ")));
                    result.append(")");
                }
                result.append(" => ");

                Statement body = le.body.get(0);
                if (body.statementKind == Statement.StatementKind.RETURN) {
                    Return ret = (Return) body;
                    result.append(convert(ret.expression));
                } else {
                    result.append(convertStatementForLambda(body, ""));
                }

                return result.toString();
            }

            case POST_INCREMENT: {
                PostIncrement pi = (PostIncrement) expression;
                Expression expr = pi.expression;
                if (pi.increment < 0) {
                    postDecrement = convert(expr);
                    return convert(expr);
                } else {
                    return convert(expr) + "++";
                }
            }

            case ARRAY_ACCESSOR: {
                ArrayAccessor aa = (ArrayAccessor) expression;
                return convert(aa.arrayExpression) + "[" + convert(aa.indexExpression) + "]";
            }

            case BINARY_OP: {
                BinaryOp bo = (BinaryOp) expression;
                if (bo.op.equals(INSTANCEOF)) {
                    throw new UnsupportedOperationException("Use of instanceof operator in JavaScript is not supported. Use 'instanceof' method call instead.");

                } else {
                    return convert(bo.left) + " " + bo.op + " " + convert(bo.right);
                }
            }

            case IF_EXPRESSION: {
                IfExpression ie = (IfExpression) expression;
                return convert(ie.condition) + " ? " + convert(ie.thenExpression) + " : " + convert(ie.elseExpression);
            }

            case ARRAY_ALLOCATOR: {
                ArrayAllocator aa = (ArrayAllocator) expression;
                return "new Array(" + convert(aa.size) + ")";
            }

            case INSTANCEOF: {
                InstanceOf ioe = (InstanceOf) expression;
                return convert(ioe.expression) + " instanceof " + convert(ioe.type);
            }

            default:
                System.out.println("Unsupported expression type: " + expression);
                throw new IllegalArgumentException("Unsupported expression type " + expression);
        }
    }

    private boolean isSimpleLambdaBody(Statement statement) {
        return statement.statementKind == Statement.StatementKind.RETURN ||
                (statement.statementKind == Statement.StatementKind.EXPRESSION_STATEMENT &&
                        ((Expression) statement).expressionKind == Expression.ExpressionKind.METHOD_CALL);
    }

    private void lateEmitMethod(Method method) {
        this.lateMethods.add(method);
    }

    private String convertConstant(Constant c) {
        return switch (c.constantType) {
            case STRING -> "\"" + c.value.toString().replace("\"", "\\\"") + "\"";
            case INTEGER -> c.value.toString();
            case LONG -> c.value.toString();
            case FLOAT -> c.value.toString();
            case DOUBLE -> c.value.toString();
            case BOOLEAN -> c.value.toString();
            case NULL -> "null";
            case BOOL -> c.value.toString();

        };
    }

    private String convertMethodCall(MethodCall mc) {
        StringBuilder result = new StringBuilder();
        switch (mc.operatorKind) {
            case CONSTRUCTOR_CALL -> {
                if (mc.clazz!=null) {
                    return emitAnonymous(mc.clazz,result) ;
                }
                assert mc.className != null;
                if (isMap(mc.className)) {
                    return "new Map()";
                }
                if (isList(mc.className)) {
                    return "[]";
                }
                result.append("new ").append(importAndGetLocalName(sanitizeName(convert(mc.className)))).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }

            case OBJECT_METHOD_CALL -> {
                assert mc.object != null;
                String convertedObject = convert(mc.object);
                String callMethodName = updateMethodNameIfOverloaded(mc, convertedObject, sanitizeName(mc.methodName));
                result.append(convertedObject).append(".").append(callMethodName).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }

            case OBJECT_ACCESSOR -> {
                if (mc.className != null) {
                    result.append(importAndGetLocalName(sanitizeName(convert(mc.className))))
                            .append(".").append(sanitizeName(mc.methodName));
                } else if (mc.object instanceof Variable) {
                    result.append(convert(mc.object)).append(".").append(sanitizeName(mc.methodName));
                } else if (mc.object instanceof MethodCall) {
                    MethodCall mc2 = (MethodCall) mc.object;
                    result.append(convert(mc2)).append(".").append(mc.methodName);
                } else {
                    throw new IllegalArgumentException("Unsupported object type in accessor: " + mc.object);
                }
                return result.toString();
            }

            case FUNCTIONAL_INTERFACE_CALL, OPERATOR_VARIABLE -> {
                assert mc.object != null;
                assert mc.methodName != null;

                if (mc.methodName.equals("forEach")) {
                    return convertArrayForEach(mc);
                }

                if (mc.operatorKind.equals(FUNCTIONAL_INTERFACE_CALL)) {
                    result.append(convert(mc.object)).append("(");
                } else {
                    String convertedObject2 = convert(mc.object);

                    String callMethodName2 = updateMethodNameIfOverloaded(mc, convertedObject2, sanitizeName(mc.methodName));
                    result.append(convertedObject2).append(".").append(callMethodName2).append("(");
                }
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }

            case STATIC_METHOD_CALL -> {
                assert mc.className != null;
                result.append(importAndGetLocalName(sanitizeName(convert(mc.className))))
                        .append(".").append(sanitizeName(mc.methodName)).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }

            case NO_OPERATOR -> {
                for (PastAnnotation ann : mc.annotation) {
                    if (ann instanceof StaticMethod) {
                        result.append(this.currentClass.name).append(".");
                    }
                }
                result.append(sanitizeName(mc.methodName)).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }
            case SUPER_METHOD_CALL -> {
                if (mc.methodName == null) {
                    result.append("super");
                } else {
                    result.append("super.")
                            .append(sanitizeName(mc.methodName));
                }
                result.append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")\n");
                return result.toString();
            }
        }
        throw new IllegalArgumentException("Unsupported method call type " + mc);
    }

    private String emitAnonymous(Class clazz, StringBuilder result) {
       // String className = "AnonymousClass" + (lambdaCount++);
     //   ClassSignature sig = typeRegistry != null ? typeRegistry.lookup(clazz.name, currentPackageName) : null;
       // if (sig != null) {
      //      className = sig.name;
      //  }
        result.append("new ");
        emit(clazz, result);
        return result.toString();

    }

    private String updateMethodNameIfOverloaded(MethodCall mc, String convertedObject, String callMethodName) {
        if ("this".equals(convertedObject) || (mc.object.inferredType instanceof ClassName)) {
            int argCount = mc.arguments == null ? 0 : mc.arguments.size();
            if (argCount!=0) {
                List<TypeName> argumentTypes= mc.arguments.stream().map(a -> a.inferredType).collect(Collectors.toList());
                String resolvedAlt;
                if ("self".equals(convertedObject)) {
                    resolvedAlt=findAltNameForCall(mc.methodName, argumentTypes);
                } else {
                    resolvedAlt=findAltNameForCall((ClassName) mc.object.inferredType, callMethodName, argumentTypes);
                }
                if (resolvedAlt != null) {
                    callMethodName = sanitizeName(resolvedAlt);
                }
            }
        }
        return callMethodName;
    }

    private String findAltNameForCall(ClassName className,String methodName, List<TypeName> argTypes) {
        if (typeRegistry==null) return null;
        ClassSignature sig=typeRegistry.lookup(className.simpleName, className.packge);
        if (sig == null) return null;
        for (MethodSignature ms : sig.methods) {
            if (!ms.name.equals(methodName)) continue;
            if (!paramTypesMatch(argTypes, ms)) continue;
            for (PastAnnotation ann : ms.getAnnotations()) {
                if (ann instanceof OverloadedMethod) return ((OverloadedMethod) ann).getAltName();
            }
        }
        return null;
    }




    // ---- OverloadedMethod alt-name resolution (mirrors Python.java) ----

    private String findAltNameForDeclaration(Method method) {
        if (currentClassSignature == null || typeRegistry == null) return null;
        int paramCount = method.parameters == null ? 0 : method.parameters.size();
        for (MethodSignature ms : currentClassSignature.methods) {
            if (!ms.name.equals(method.name)) continue;
            if (ms.parameterTypes.size() != paramCount) continue;
            for (PastAnnotation ann : ms.getAnnotations()) {
                if (ann instanceof OverloadedMethod) {
                    if (paramCount == 0 || paramTypesMatch(method, ms)) {
                        return ((OverloadedMethod) ann).getAltName();
                    }
                }
            }
        }
        return null;
    }

    private String findAltNameForCall(String methodName, List<TypeName> argTypes) {
        if (currentClassSignature == null || typeRegistry == null) return null;
        for (MethodSignature ms : currentClassSignature.methods) {
            if (!ms.name.equals(methodName)) continue;
            if (!paramTypesMatch(argTypes, ms)) continue;
            for (PastAnnotation ann : ms.getAnnotations()) {
                if (ann instanceof OverloadedMethod) return ((OverloadedMethod) ann).getAltName();
            }
        }
        return null;
    }

    private boolean paramTypesMatch(Method method, MethodSignature ms) {
        if (method.parameters.size() != ms.parameterTypes.size()) return false;
        List<TypeName> argTypes = new ArrayList<>();
        for (Parameter p : method.parameters) argTypes.add(p.type);
        return paramTypesMatch(argTypes, ms);
    }

    private boolean paramTypesMatch(List<TypeName> argTypes, MethodSignature ms) {
        if (argTypes.size() != ms.parameterTypes.size()) return false;
        for (int i = 0; i < argTypes.size(); i++) {
            String argTypeName = typeSimpleName(argTypes.get(i)).toLowerCase();
            String regTypeName = typeSimpleName(ms.parameterTypes.get(i)).toLowerCase();
            if (!argTypeName.equals(regTypeName)) return false;
        }
        return true;
    }

    private static String typeSimpleName(TypeName type) {
        if (type instanceof ClassName) return ((ClassName) type).simpleName;
        if (type instanceof ParameterizedType) return ((ParameterizedType) type).getRawType().simpleName;
        if (type instanceof ArrayType) return typeSimpleName(((ArrayType) type).elementType) + "Array";
        if (type instanceof TypeVariable) return ((TypeVariable) type).name;
        return type.toString();
    }

    private String convertArrayForEach(MethodCall mc) {
        Expression expression = mc.arguments.get(0);
        LambdaExpression le = (LambdaExpression) expression;
        StringBuilder result = new StringBuilder();

        result.append(convert(mc.object)).append(".forEach(")
                .append(sanitizeName(le.parameters.get(0).name))
                .append(" => {\n");

        for (Statement stmt : le.body) {
            result.append(INDENT + INDENT + INDENT);
            if (stmt.statementKind == Statement.StatementKind.RETURN) {
                Return ret = (Return) stmt;
                result.append(convert(ret.expression));
            } else {
                result.append(convertStatementForLambda(stmt, ""));
            }
            result.append(";\n");

            if (postDecrement != null) {
                result.append(INDENT + INDENT + INDENT)
                        .append(postDecrement)
                        .append("--;\n");
                postDecrement = null;
            }
        }

        result.append(INDENT + INDENT).append("})");
        return result.toString();
    }

    private String convertLH(Expression leftHandExpression) {
        if (leftHandExpression instanceof Variable) {
            Variable ve = (Variable) leftHandExpression;
            return ve.name;
        } else if (leftHandExpression instanceof MethodCall) {
            MethodCall mc = (MethodCall) leftHandExpression;
            return convertMethodCall(mc);
        } else if (leftHandExpression instanceof ArrayAccessor) {
            ArrayAccessor aa = (ArrayAccessor) leftHandExpression;
            return convert(aa.arrayExpression) + "[" + convert(aa.indexExpression) + "]";
        }
        throw new IllegalArgumentException("Unsupported left-hand expression type");
    }

    private String convert(TypeName tn) {
        switch (tn.typeKind) {
            case CLASS: {
                ClassName cn = (ClassName) tn;
                if (cn.packge != null && !cn.packge.isEmpty()) {
                    if (cn.packge.equals("past.lang")) {
                        return switch (cn.simpleName) {
                            case "String" -> "String";
                            case "Integer", "int" -> "Number";
                            case "Float" -> "Number";
                            case "Boolean" -> "Boolean";
                            case "Object" -> "Object";
                            default -> (cn.packge + "." + cn.simpleName);
                        };
                    }
                    return cn.packge + "." + cn.simpleName;
                } else {
                    return cn.simpleName;
                }
            }
            case VARIABLE:
            case ARRAY:
            case PARAMETERIZED:
            default:
                return tn.toString();
        }
    }

    private String convertForInstanceCheck(TypeName tn) {
        switch (tn.typeKind) {
            case CLASS: {
                ClassName cn = (ClassName) tn;
                if (cn.packge != null && cn.packge.equals("past.lang")) {
                    return switch (cn.simpleName) {
                        case "String" -> "String";
                        case "Integer", "int" -> "Number";
                        case "Float" -> "Number";
                        case "Boolean" -> "Boolean";
                        case "Object" -> "Object";
                        default -> (cn.packge + "." + cn.simpleName);
                    };
                }
                return cn.packge + "." + cn.simpleName;
            }
            case VARIABLE:
            case ARRAY:
            case PARAMETERIZED:
            default:
                throw new IllegalArgumentException("Unsupported type for instanceof: " + tn);
        }
    }

    private List<String> convert(Comment c) {
        return List.of(String.format(c.format.replace("$L", "%s").replace("$N", "%s"), c.objects).split("\n"));
    }

    private String convertVariableName(String name) {
        if (name.equals("this")) {
            return "this";
        } else if (name.equals("throw")) {
            return "throw";
        } else {
            return name;
        }
    }

    private boolean isMap(TypeName typeName) {
        switch (typeName.typeKind) {
            case CLASS:
                ClassName cn = (ClassName) typeName;
                String fullName = (cn.packge != null && !cn.packge.isEmpty()) ? (cn.packge + "." + cn.simpleName) : cn.simpleName;
                return fullName.equals("past.util.Map") || fullName.equals("past.util.HashMap");
            case PARAMETERIZED:
                ParameterizedType pt = (ParameterizedType) typeName;
                return isMap(pt.rawType);
            default:
                return false;
        }
    }

    private boolean isList(TypeName typeName) {
        switch (typeName.typeKind) {
            case CLASS:
                ClassName cn = (ClassName) typeName;
                String fullName = (cn.packge != null && !cn.packge.isEmpty()) ? (cn.packge + "." + cn.simpleName) : cn.simpleName;
                return fullName.equals("past.util.List") || fullName.equals("past.util.LinkedList") || fullName.equals("past.util.ArrayList");
            case PARAMETERIZED:
                ParameterizedType pt = (ParameterizedType) typeName;
                return isList(pt.rawType);
            default:
                return false;
        }
    }

    private String getLocalName(String imprt) {
        return switch (imprt) {
            case "past.lang.String" -> "String";
            case "past.lang.Integer" -> "int";
            case "past.lang.Float" -> "float";
            case "past.lang.Boolean" -> "bool";
            case "past.lang.Double" -> "float";
            default -> imprt.substring(imprt.lastIndexOf('.') + 1);
        };
    }

    private String importAndGetLocalName(String imprt) {
        imports.add(imprt);
        return getLocalName(imprt);
    }

    private boolean hasRequiredInitializer(Field field) {
        return !field.annotation.isEmpty();
    }

    Map<String, String> functionNameConversion = new HashMap<>() {{
        put("Integer.valueOf", "parseInt");
        put("Long.valueOf", "parseInt");
        put("Float.valueOf", "parseFloat");
        put("Double.valueOf", "parseFloat");
        put("Boolean.valueOf", "Boolean");
        put("add", "push");
        put("class", "constructor");
    }};

    private String sanitizeName(String name) {
        if (name == null) return "unknown";
        if (functionNameConversion.containsKey(name)) {
            return functionNameConversion.get(name);
        }
        //if (name.startsWith(GENERATED_VAR_PREFIX)) {
         //   return name.substring(2);
        //}

        // Handle reserved JavaScript keywords
        if (isJavaScriptKeyword(name)) {
            return name + "_";
        }
        return name;
    }

    private boolean isJavaScriptKeyword(String name) {
        return List.of("abstract", "arguments", "await", "boolean", "break", "byte", "case",
                        "catch", "char", "class", "const", "continue", "debugger", "default",
                        "delete", "do", "double", "else", "enum", "eval", "export", "extends",
                        "false", "final", "finally", "float", "for", "function", "goto", "if",
                        "implements", "import", "in", "instanceof", "int", "interface", "let",
                        "long", "native", "new", "null", "package", "private", "protected",
                        "public", "return", "short", "static", "super", "switch", "synchronized",
                        //"this",
                        "throw", "throws", "transient", "true", "try", "typeof", "var",
                        "void", "volatile", "while", "with", "yield")
                .contains(name);
    }

    private void delayedImport(StringBuilder sb, String indent, String imprt) {
        String localName = getLocalName(imprt);
        String importPath = "./" + imprt.replace('.', '/');
        sb.append(indent).append("const { ").append(localName).append(" } = await import('")
                .append(importPath).append(".js');\n");
    }
}
