package org.openprovenance.prov.template.compiler.past.emitter;


import org.openprovenance.prov.template.compiler.past.*;
import org.openprovenance.prov.template.compiler.past.Class;
import org.openprovenance.prov.template.compiler.past.type.ClassName;
import org.openprovenance.prov.template.compiler.past.type.TypeName;

import java.io.File;
import java.io.IOException;
import javax.lang.model.element.Modifier;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;

import static org.openprovenance.prov.template.compiler.common.Constants.LOGGER;
import static org.openprovenance.prov.template.compiler.past.MethodCall.MethodCallKind.FUNCTIONAL_INTERFACE_CALL;
import static org.openprovenance.prov.template.compiler.past.Variable.VARIABLE;

/**
 * Emitter that generates Python class definitions from PAST abstract syntax tree.
 * Mirrors the Poet.java approach but outputs Python syntax.
 */
public class Python implements Emitter<StringBuilder> {
    private StringBuilder sb;
    private static final String INDENT = "    ";
    private int lambdaCount=0;


    public StringBuilder specWithComment(StringBuilder sb, String templateName, String packge, StackTraceElement stackTraceElement) {
        sb.insert(0, "# Generated by ProvToolbox for template '" + templateName + "'\n"
                + "# by class " + stackTraceElement.getClassName() + ", method " + stackTraceElement.getMethodName() +
                ",\n# in file " + stackTraceElement.getFileName() + ", at line " + stackTraceElement.getLineNumber() + "\n\n");
        return sb;
    }

    public WritableObject toWritableObject(Class clazz, String templateName, String packge, StackTraceElement stackTraceElement) {
        StringBuilder theBuffer=emit(clazz);

        specWithComment(theBuffer, templateName, packge, stackTraceElement);
        return new WritableObject() {
            @Override
            public void writeTo(File directory) throws IOException {
                Path destination = Paths.get(directory.getAbsolutePath()).resolve(packge.replace('.', '/'));
                destination.toFile().mkdirs();
                java.nio.file.Path path = destination.resolve(clazz.name + ".py");
                java.nio.file.Files.writeString(path, theBuffer.toString());
            }
        };
    }

    List<String> imports;
    @Override
    public StringBuilder emit(Class clazz) {
        this.sb = new StringBuilder();

        imports = new java.util.ArrayList<>();

        // Class docstring from comments

        sb.append("\"\"\"");
        sb.append(clazz.comments.stream().map(this::convert).collect(Collectors.joining("\n")));
        sb.append("\"\"\"\n");


        // Class declaration
        sb.append("class ").append(sanitizeName(clazz.name));

        // Base classes (interfaces in Java become base classes in Python)
        if (!clazz.interfaces.isEmpty()) {
            sb.append("(");
            sb.append(clazz.interfaces.stream()
                    .map(this::convert)
                    .map(this::sanitizeName)
                    .map( f -> {
                        imports.add(f);
                        return getLocalName(f);
                    })
                    .collect(Collectors.joining(", ")));
            sb.append(")");
        }
        sb.append(":\n");

        boolean hasContent = false;


        // Constructor (__init__)
        if (!clazz.fields.isEmpty()) {
            emitConstructor(clazz.fields);
            hasContent = true;
        }

        // Methods
        if (!clazz.methods.isEmpty()) {
            for (Method method : clazz.methods) {
                emitMethod(method);
                hasContent = true;
            }
        }

        for (Method method: lateMethods) {
            emitMethod(method);
            hasContent = true;
        }




        // Empty class body
        if (!hasContent) {
            sb.append(INDENT).append("pass\n");
        }

        for (String imprt : imports) {
            // get suffix after last dot in imprt
            String suffix = getLocalName(imprt);
            // ignore LOGGER
            if (LOGGER.equals(suffix)) continue;
            sb.insert(0, "from " + imprt + " import " + suffix + "\n");
        }

        return sb;
    }

    List<Method> lateMethods=new java.util.ArrayList<>();
    private void lateEmitMethod(Method method) {
        this.lateMethods.add(method);
    }
    private String getLocalName(String imprt) {
        return imprt.substring(imprt.lastIndexOf('.') + 1);
    }
    private String importAndGetLocalName(String imprt) {
        imports.add(imprt);
        return getLocalName(imprt);
    }

    private String convert(TypeName tn) {
        switch (tn.typeKind) {
            case CLASS: {
                ClassName cn = (ClassName) tn;
                if (cn.packge!=null && !cn.packge.isEmpty()) {
                    return(cn.packge + "." + cn.simpleName);
                    //return cn.simpleName;
                } else {
                    return cn.simpleName;
                }
            }
            case VARIABLE:
            case ARRAY:
            case PARAMETERIZED:
            default: return (tn.toString());
        }

    }

    private String convert(Comment c) {
        return String.format(c.format.replace("$L","%s").replace("$N","%s"), c.objects);
    }

    private void emitConstructor(List<Field> fields) {
        sb.append(INDENT).append("def __init__(self");

        // Parameters from fields
        for (Field field : fields) {
            if (!isStaticOrFinal(field)) {
                sb.append(", ").append(sanitizeName(field.name));
                sb.append("=None");
            }
        }
        sb.append("):\n");

        boolean anyField=false;
        // Field assignments
        for (Field field : fields) {
            String fieldName = sanitizeName(field.name);
            if (!field.modifiers.contains(Modifier.STATIC)) {
                anyField=true;
                if (field.modifiers.contains(Modifier.FINAL)) {
                    sb.append(INDENT).append(INDENT)
                            .append("self.").append(fieldName)
                            .append(" = ").append(convert(field.initialiser)).append("\n");
                } else {

                    sb.append(INDENT).append(INDENT)
                            .append("self.").append(fieldName)
                            .append(" = ").append(fieldName).append("\n");
                }
            }
        }
        if (!anyField) {
            sb.append(INDENT).append(INDENT).append("pass\n");
        }
        sb.append("\n");
        for (Field field : fields) {
            String fieldName = sanitizeName(field.name);
            if (field.modifiers.contains(Modifier.STATIC)) {
                sb.append(INDENT)
                        .append(fieldName)
                        .append(" = ").append(convert(field.initialiser)).append("\n");
            }
        }
    }

    private void emitMethod(Method method) {
        // Method docstring
        if (method.comments != null && !method.comments.isEmpty()) {
            sb.append(INDENT).append("\"\"\"");
            sb.append(method.comments.stream().map(this::convert).collect(Collectors.joining("\n" + INDENT)));
            sb.append("\"\"\"\n");
        }

        if (method.modifiers.contains(Modifier.STATIC)) {
            sb.append(INDENT).append("@staticmethod\n");
        }

        // Method signature
        sb.append(INDENT).append("def ").append(sanitizeName(method.name));
        sb.append("(");
        if (method.modifiers.contains(Modifier.STATIC)) {
            sb.append("cls");
        } else {
            sb.append("self");
        }

        // Parameters
        if (method.parameters != null) {
            for (var param : method.parameters) {
                sb.append(", ").append(sanitizeName(param.name));
            }
        }
        sb.append("):\n");

        // Method body placeholder

        method.body.forEach(statement -> {
            // Here we would convert each statement to Python code
            // For now, we just add a placeholder comment
            emitStatement (statement, INDENT + INDENT);
        });
        sb.append(INDENT).append(INDENT).append("pass\n\n");


    }

    String postDecrement=null;

    private void emitStatement(Statement statement, String indent) {
        switch (statement.statementKind) {
            case ASSIGNMENT -> {
                Assignment assignment = (Assignment) statement;
                if (assignment.leftHandExpression instanceof Variable
                        && ((Variable)assignment.leftHandExpression).name.equals("self")) {
                    return;
                }
                sb.append(indent)
                        .append(sanitizeName(convertLH(assignment.leftHandExpression)))
                        .append(" = ")
                        .append(sanitizeName(convert(assignment.value)))
                        .append("\n");

                if (postDecrement!=null) {
                    sb.append(indent)
                            .append(postDecrement)
                            .append(" -= 1")
                            .append("\n");
                    postDecrement=null;
                }

            }

            case RETURN -> {
                Return ret = (Return) statement;
                sb.append(indent)
                        .append("return ")
                        .append(sanitizeName(convert(ret.expression)))
                        .append("\n");

            }
            case COMMENT -> {
                Comment cs = (Comment) statement;
                sb.append(indent)
                        .append("# ")
                        .append(convert(cs))
                        .append("\n");
            }
            case EXPRESSION_STATEMENT -> {
                Expression es = (Expression) statement;
                sb.append(indent)
                        .append(sanitizeName(convert(es)))
                        .append("\n");
            }
            case IF_STATEMENT -> {
                IfStatement ifs = (IfStatement) statement;
                sb.append(indent)
                        .append("if ")
                        .append(convert(ifs.condition))
                        .append(":\n");
                if (ifs.thenBlock.isEmpty()) {
                    sb.append(indent).append(INDENT).append("pass\n");
                } else {
                    for (Statement thenStmt : ifs.thenBlock) {
                        emitStatement(thenStmt, indent + INDENT);
                    }
                }
                if (!ifs.elseBlock.isEmpty()) {
                    sb.append(indent)
                            .append("else:\n");
                    for (Statement elseStmt : ifs.elseBlock) {
                        emitStatement(elseStmt, indent + INDENT);
                    }
                }
            }

            case FOR_LOOP -> {
                ForLoop forLoop = (ForLoop) statement;
                Statement initialization = forLoop.initialization;
                Expression condition = forLoop.condition;
                Statement update = forLoop.update;
                emitStatement(initialization, INDENT+INDENT);
                sb.append(indent)
                        .append("while (")
                        .append(convert(condition))
                        .append("):\n");
                for (Statement bodyStmt : forLoop.body) {
                    emitStatement(bodyStmt, indent + INDENT);
                }
                emitStatement(update, indent + INDENT);

            }

            default -> {
                throw new IllegalArgumentException("Unsupported statement type " + statement);
            }
        }
    }

    private String convertStatementForLambda(Statement statement, String indent) {
        StringBuilder sb=new StringBuilder();
        switch (statement.statementKind) {
            case ASSIGNMENT -> {
                Assignment assignment = (Assignment) statement;
                sb.append(indent)
                        .append(sanitizeName(convertLH(assignment.leftHandExpression)))
                        .append(" = ")
                        .append(sanitizeName(convert(assignment.value)));
            }
            case EXPRESSION_STATEMENT -> {
                Expression es = (Expression) statement;
                MethodCall mc=(MethodCall) es;
                sb.append(indent).append(convertMethodCall(mc));
            }

            default -> {
                throw new IllegalArgumentException("Unsupported statement type " + statement);
            }
        }
        return sb.toString();
    }

    private String convert(Expression expression) {
        switch (expression.expressionKind) {
            case VARIABLE: {
                Variable ve = (Variable) expression;
                return switch (ve.field) {
                    case STATIC_FIELD_VARIABLE -> "cls." + sanitizeName(ve.name);
                    case FIELD_VARIABLE -> "self." + sanitizeName(ve.name);
                    case LOCAL_VARIABLE -> convertVariableName(sanitizeName(ve.name));
                };
            }
            case CONSTANT: {
                Constant constant = (Constant) expression;
                return convertConstant(constant);
            }
            case METHOD_CALL: {
                MethodCall mc = (MethodCall) expression;
                return convertMethodCall(mc);
            }
            case ARRAY_INITIALISER: {
                ArrayInitialiser ai = (ArrayInitialiser) expression;
                StringBuilder result = new StringBuilder();
                result.append("[");
                result.append(ai.values.stream()
                        .map(this::convert)
                        .map(this::sanitizeName)
                        .collect(Collectors.joining(", ")));
                result.append("]");
                return result.toString();
            }
            case CAST: {
                CastExpression c = (CastExpression) expression;
                // ignore type in Python
                return convert(c.expression);
            }
            case LAMBDA_EXPRESSION: {
                LambdaExpression le = (LambdaExpression) expression;
                if (le.body.size() != 1) {
                    String funName="funLambda" + (lambdaCount++);
                    Method method=new Method(funName);
                    method.parameters.addAll(le.parameters);
                    method.body.addAll(le.body);
                    
                    lateEmitMethod(method);

                    LambdaExpression le2=new LambdaExpression(le.parameters);
                    le2.body.add(
                            new MethodCall("self."+funName, le.parameters.stream().map(p -> new Variable(p.name)).collect(Collectors.toList())));

                   le=le2;
                }
                StringBuilder result = new StringBuilder();
                result.append("lambda ");
                result.append(le.parameters.stream()
                        .map(p -> sanitizeName(p.name))
                        .collect(Collectors.joining(", ")));
                result.append(": ");
                if (le.body.size() != 1) {
                    throw new IllegalArgumentException("Only single-expression lambdas are supported in this emitter");
                }
                result.append(convertStatementForLambda(le.body.get(0), INDENT));
                return result.toString();
            }
            case POST_INCREMENT: {
                PostIncrement pi = (PostIncrement) expression;
                Expression expre = pi.expression;
                if (pi.increment<0) {
                    postDecrement=convert(expre);
                    return convert(expre);
                } else {
                    return convert(expre) + "++";
                }
            }
            case ARRAY_ACCESSOR: {
                ArrayAccessor aa = (ArrayAccessor) expression;
                return convert(aa.arrayExpression) + "[" + convert(aa.indexExpression) + "]";
            }
            case BINARY_OP: {
                BinaryOp bo = (BinaryOp) expression;
                return convert(bo.left) + " " + bo.op + " " + convert(bo.right);
            }

            default:
               throw new IllegalArgumentException("Unsupported expression type " + expression);
        }
    }

    private String convertVariableName(String name) {
        if (name.equals("this")) {
            return "self";
        } else {
            return name;
        }
    }


    private String convertConstant(Constant c) {
        return switch (c.constantType) {
            case STRING -> "\"" + c.value.toString() + "\"";
            case INTEGER -> c.value.toString();
            case FLOAT -> c.value.toString();
            case BOOLEAN -> c.value.toString();
            case NULL -> "0";
        };
    }

    private String convertMethodCall(MethodCall mc) {
        StringBuilder result= new StringBuilder();
        switch(mc.operatorKind) {
            case CONSTRUCTOR_CALL -> {
                assert mc.className!=null;
                result.append(importAndGetLocalName(sanitizeName(convert(mc.className)))).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .map(this::sanitizeName)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }
            case OBJECT_METHOD_CALL -> {
                assert mc.object!=null;
                result.append(convert(mc.object)).append(".").append(sanitizeName(mc.methodName)).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .map(this::sanitizeName)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }
            case OBJECT_ACCESSOR -> {
                if (mc.className != null) {
                    //                    return CodeBlock.of("$T.$L", convert(methodCall.className), methodCall.methodName);
                    result.append(importAndGetLocalName(sanitizeName(convert(mc.className)))).append(".").append(sanitizeName(mc.methodName));
                } else  if (mc.object instanceof Variable) {
                    result.append(convert(mc.object)).append(".").append(sanitizeName(mc.methodName));
                } else {
                    throw new IllegalArgumentException("Unsupported object type in accessor: " + mc.object);
                }
                return result.toString();
            }

            case FUNCTIONAL_INTERFACE_CALL, OPERATOR_VARIABLE -> {
                assert mc.object!=null;
                assert mc.methodName!=null;
                if (mc.methodName.equals("forEach")) {
                  return convertListForEach(mc);
                }
                if (mc.operatorKind.equals(FUNCTIONAL_INTERFACE_CALL)) {
                    // methodName is a method of a functional interface. In python, the function is called directly instead, without naming a method
                    result.append(convert(mc.object)).append("(");
                } else {
                    result.append(convert(mc.object)).append(".").append(sanitizeName(mc.methodName)).append("(");
                }
                if (mc.arguments != null) {

                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .map(this::sanitizeName)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }
            case STATIC_METHOD_CALL -> {
                assert mc.className!=null;
                result.append(importAndGetLocalName(sanitizeName(convert(mc.className)))).append(".").append(sanitizeName(mc.methodName)).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .map(this::sanitizeName)

                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }
            case NO_OPERATOR -> {
                result.append(sanitizeName(mc.methodName)).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .map(this::sanitizeName)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }

        }
        throw new IllegalArgumentException("Unsupported method call type " + mc);

    }

    private String convertListForEach(MethodCall mc) {
        Expression expression = mc.arguments.get(0);
        LambdaExpression le = (LambdaExpression) expression;
        StringBuilder sb=new StringBuilder();
        sb.append("for ").append(sanitizeName(le.parameters.get(0).name)).append(" in ").append(convert(mc.object)).append(":\n");
        for (Statement stmt: le.body) {
            sb.append(convertStatementForLambda(stmt,INDENT + INDENT + INDENT));
            sb.append("\n");
            if (postDecrement!=null) {
                sb.append(INDENT + INDENT + INDENT)
                        .append(postDecrement)
                        .append(" -= 1")
                        .append("\n");
                postDecrement=null;
                sb.append("\n");
            }
        }
        return sb.toString();
    }

    private String convertLH(Expression leftHandExpression) {

        if (leftHandExpression instanceof Variable) {
            Variable ve = (Variable) leftHandExpression;
            return ve.name;
        } else if (leftHandExpression instanceof MethodCall) {
            MethodCall mc = (MethodCall) leftHandExpression;
            return convertMethodCall(mc);
        }
        throw new IllegalArgumentException("Unsupported left-hand expression type");
    }


    private boolean isStaticOrFinal(Field field) {
        return field.modifiers.contains(Modifier.STATIC) ||
                field.modifiers.contains(Modifier.FINAL);
    }

    private String sanitizeName(String name) {
        if (name == null) return "unknown";
        // Convert Java naming to Python (camelCase to snake_case)
        if (name.equals("None")) {
            return "None";
        }
        if (name.equals("add")) {
            return "append";
        }
        //String result = name.replaceAll("([a-z])([A-Z])", "$1_$2").toLowerCase();
        String result=name;
        // Handle reserved keywords
        if (isPythonKeyword(result)) {
            result = result + "_";
        }
        return result;
    }

    private boolean isPythonKeyword(String name) {
        return List.of("and", "as", "assert", "break", "class", "continue",
                        "def", "del", "elif", "else", "except", "finally",
                        "for", "from", "global", "if", "import", "in",
                        "is", "lambda", "nonlocal", "not", "or", "pass",
                        "raise", "return", "try", "while", "with", "yield")
                .contains(name);
    }

}
