package org.openprovenance.prov.template.compiler.past.emitter;


import org.openprovenance.prov.template.compiler.past.*;
import org.openprovenance.prov.template.compiler.past.Class;
import org.openprovenance.prov.template.compiler.past.Iterator;
import org.openprovenance.prov.template.compiler.past.annotations.*;
import org.openprovenance.prov.template.compiler.past.annotations.OverloadedMethod;
import org.openprovenance.prov.template.compiler.past.checker.ClassSignature;
import org.openprovenance.prov.template.compiler.past.checker.MethodSignature;
import org.openprovenance.prov.template.compiler.past.checker.TypeRegistry;
import org.openprovenance.prov.template.compiler.past.type.ArrayType;
import org.openprovenance.prov.template.compiler.past.type.ClassName;
import org.openprovenance.prov.template.compiler.past.type.ParameterizedType;
import org.openprovenance.prov.template.compiler.past.type.TypeName;
import org.openprovenance.prov.template.compiler.past.type.TypeVariable;

import java.io.File;
import java.io.IOException;
import javax.lang.model.element.Modifier;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.stream.Collectors;

import static org.openprovenance.prov.template.compiler.common.Constants.GENERATED_VAR_PREFIX;
import static org.openprovenance.prov.template.compiler.common.Constants.LOGGER;
import static org.openprovenance.prov.template.compiler.past.Assignment.ASSIGNMENT;
import static org.openprovenance.prov.template.compiler.past.BinaryOp.INSTANCEOF;
import static org.openprovenance.prov.template.compiler.past.Method.METHOD;
import static org.openprovenance.prov.template.compiler.past.MethodCall.METHOD_CALL;
import static org.openprovenance.prov.template.compiler.past.MethodCall.MethodCallKind.FUNCTIONAL_INTERFACE_CALL;
import static org.openprovenance.prov.template.compiler.past.Variable.VARIABLE;
import static org.openprovenance.prov.template.compiler.past.type.ClassName.INTEGER;

/**
 * Emitter that generates Python class definitions from PAST abstract syntax tree.
 * Mirrors the Poet.java approach but outputs Python syntax.
 */
public class Python implements Emitter<StringBuilder> {
    private final TypeRegistry typeRegistry;
    private StringBuilder sb;
    private static final String INDENT = "    ";
    private int lambdaCount=0;
    private String currentPackageName;
    private ClassSignature currentClassSignature;
    private String currentClassName;

    public Python(TypeRegistry registry) {
        this.typeRegistry = registry;
    }


    public StringBuilder addHeader(StringBuilder sb, String templateName, String packge, StackTraceElement stackTraceElement) {
        sb.insert(0, "# Generated by ProvToolbox for template configuration '" + templateName + "'\n"
                + "# by class " + stackTraceElement.getClassName() + ", method " + stackTraceElement.getMethodName() +
                ",\n# in file " + stackTraceElement.getFileName() + ", at line " + stackTraceElement.getLineNumber() + "\n\n");
        return sb;
    }

    public WritableObject toWritableObject(Class clazz, String className, String packge, StackTraceElement stackTraceElement) {
        this.currentPackageName = packge;
        this.currentClassName=className;
        StringBuilder theBuffer=emit(clazz);

        addHeader(theBuffer, className, packge, stackTraceElement);
        return new WritableObject() {
            @Override
            public void writeTo(File directory) throws IOException {
                Path destination = Paths.get(directory.getAbsolutePath()).resolve(packge.replace('.', '/'));
                destination.toFile().mkdirs();
                java.nio.file.Path path = destination.resolve(clazz.name + ".py");
                java.nio.file.Files.writeString(path, theBuffer.toString());
            }
        };
    }

    Set<String> imports;
    @Override
    public StringBuilder emit(Class clazz) {
        this.sb = new StringBuilder();
        return emit(clazz, sb);
    }

    public StringBuilder emit(Class clazz, StringBuilder sb) {
        this.currentClassSignature = (typeRegistry != null && currentPackageName != null)
                ? typeRegistry.lookup(clazz.name, currentPackageName) : null;

        imports = new java.util.HashSet<>();
        imports.add("past.util.Map");
        imports.add("past.util.List");

        // Class docstring from comments

        sb.append("\"\"\"");
        sb.append(clazz.comments.stream().map(this::convert).flatMap(Collection::stream).collect(Collectors.joining("\n")));
        sb.append("\"\"\"\n");


        // Class declaration
        sb.append("class ").append(sanitizeName(clazz.name));


        // Base classes (interfaces in Java become base classes in Python)
        // ignored for now
        sb.append(":\n");


        // Constructor (__init__)

        if (clazz.constructors.isEmpty()) {
            emitDefaultConstructor(clazz.fields);
        } else {
            for (Constructor constructor : clazz.constructors) {
                String constructorName="____init__"; // note the quadruple _ because the first two will be removed in sanitizeName, and we want to end up with __init__
                // "python:@OverloadedMethod" in annotations
                boolean overloaded=false;
                if (constructor.annotation != null) {
                    Optional<PythonAnnotation> annotation=constructor.annotation.stream()
                            .filter(annot -> annot instanceof PythonAnnotation)
                            .map(annot -> (PythonAnnotation) annot)
                            .filter(annot -> OverloadedMethod.NAME.equals(annot.getName()))
                            .findFirst()
                            ;
                    if (annotation.isPresent()) {
                        constructorName= ((OverloadedMethod) annotation.get()).getAltName();
                        overloaded=true;
                        //System.out.println("Constructor with @OverloadedMethod annotation, using alt name: " + constructorName);
                    }
                }
                Method pythonMethodAsConstructor = METHOD(constructorName)
                        .PARAMETERS(constructor.parameters)
                        .MODIFIERS(constructor.modifiers.toArray(new Modifier[0]))
                        .BODY(constructor.body.toArray(new Statement[0]))
                        //.ANNOTATIONS(constructor.annotation.toArray(new String[0]))
                        .COMMENTS(constructor.comments.toArray(new Comment[0]));

                for (Field field : clazz.fields) {
                    String fieldName = sanitizeName(field.name);
                    if (!field.modifiers.contains(Modifier.STATIC)) {
                        if (field.initialiser != null) {
                            pythonMethodAsConstructor.BODY(
                                    ASSIGNMENT(METHOD_CALL(VARIABLE("this"), fieldName), field.initialiser));

                        }
                    }
                }
                if (overloaded) {
                    pythonMethodAsConstructor.COMMENT("Note: this method was originally a PAST constructor, but was renamed to avoid name clashes due to overloading. \n It will not be recognized as a constructor by Python code, so it should be called explicitly by its name.");
                }
                emitMethod(pythonMethodAsConstructor);
            }
        }

        // Methods
        if (!clazz.methods.isEmpty()) {
            for (Method method : clazz.methods) {
                emitMethod(method);
            }
        }

        for (Method method: lateMethods) {
            emitMethod(method);
        }


        emitStaticFields(clazz.fields);


        if (!imports.isEmpty()) {
            sb.insert(0,"\n");
            sb.insert(0,"\n");
        }

        for (String imprt : imports) {
            // get suffix after last dot in imprt
            if (!imprt.contains(".")) continue;

            String suffix = getLocalName(imprt);
            // ignore LOGGER
            if (LOGGER.equals(suffix)) continue;
            if (imprt.startsWith(INTEGER.packge)) continue;
            //functools.singledispatch
            if (imprt.equals("functools.singledispatch")) {
                sb.insert(0, "from functools import singledispatch, update_wrapper\n");
            } else {
                sb.insert(0, "from " + imprt + " import " + suffix + "\n");
            }
        }

        if (!lateEmittedClasses.isEmpty()) {
            List<LateEmittedClass> tmp=lateEmittedClasses.stream().map(c -> c).collect(Collectors.toList());
            lateEmittedClasses.clear();
            sb.append("\n\n");

            for (Class lateClazz : tmp) {
                sb.append("# Late emitted class due to anonymous class\n");
                emit(lateClazz,sb);
                sb.append("\n\n");
            }
        }
        return sb;
    }

    List<Method> lateMethods=new java.util.ArrayList<>();
    private void lateEmitMethod(Method method) {
        this.lateMethods.add(method);
    }
    private String getLocalName(String imprt) {
        return switch (imprt) {
            case "past.lang.String" -> "str";
            case "past.lang.Integer" -> "int";
            case "past.lang.Float" -> "float";
            case "past.lang.Boolean" -> "bool";
            case "past.lang.Double" -> "float";
            default -> imprt.substring(imprt.lastIndexOf('.') + 1);
        };
    }
    private String importAndGetLocalName(String imprt) {
        imports.add(imprt);
        return getLocalName(imprt);
    }

    private String convert(TypeName tn) {
        switch (tn.typeKind) {
            case CLASS: {
                ClassName cn = (ClassName) tn;
                if (cn.packge!=null && !cn.packge.isEmpty()) {
                    return(cn.packge + "." + cn.simpleName);
                    //return cn.simpleName;
                } else {
                    return cn.simpleName;
                }
            }
            case VARIABLE:
            case ARRAY:
            case PARAMETERIZED:
            default: return (tn.toString());
        }

    }


    private String convertForInstanceCheck(TypeName tn) {
        switch (tn.typeKind) {
            case CLASS: {
                ClassName cn = (ClassName) tn;
                if (cn.packge != null && cn.packge.equals("past.lang")) {
                    // map past.lang types to python types
                    return switch (cn.simpleName) {
                        case "String" -> "str";
                        case "Integer", "int" -> "int";
                        case "Float" -> "float";
                        case "Boolean" -> "bool";
                        case "Object" -> "object";
                        default -> (cn.packge + "." + cn.simpleName);
                    };
                } else if (cn.packge != null && cn.packge.equals("org.openprovenance.prov.model")) {
                    return (cn.packge + "." + cn.simpleName);
                }
            }
            case VARIABLE:
            case ARRAY:
            case PARAMETERIZED:
            default: throw new IllegalArgumentException("Unsupported type for instanceof: " + tn);
        }
    }


    private List<String> convert(Comment c) {
        return List.of(String.format(c.format.replace("$L", "%s").replace("$N", "%s"), c.objects).split("\n"));
    }

    private void emitDefaultConstructor(List<Field> fields) {
        sb.append(INDENT).append("def __init__(self");

        // Parameters from fields
        for (Field field : fields) {
            if (!isStaticOrFinal(field)) {
                if (!field.annotation.isEmpty()) {
                    for (PastAnnotation annot : field.annotation) {
                        if (annot instanceof PythonAnnotation) {
                            if (annot.getName().equals("@ClassInitialiser")) {
                                throw new IllegalArgumentException("Unexpected @ClassInitialiser annotation on dynamic field field");
                            }
                        }
                    }
                }
                sb.append(", ").append(sanitizeName(field.name));
                sb.append("=None");
            }
        }
        sb.append("):\n");

        boolean anyField=false;
        // Field assignments
        for (Field field : fields) {
            String fieldName = sanitizeName(field.name);
            if (!field.modifiers.contains(Modifier.STATIC)) {
                anyField=true;
                if (field.initialiser!=null ) { // was field.modifiers.contains(Modifier.FINAL)
                    sb.append(INDENT).append(INDENT)
                            .append("self.").append(fieldName)
                            .append(" = ").append(convert(field.initialiser)).append("\n");
                } else {

                    sb.append(INDENT).append(INDENT)
                            .append("self.").append(fieldName)
                            .append(" = ").append(fieldName).append("\n");
                }
            }
        }
        if (!anyField) {
            sb.append(INDENT).append(INDENT).append("pass\n");
        }
        sb.append("\n");

        // append json serialization method
        /*
          def toJSON(self):
        return json.dumps(
            self,
            default=lambda o: o.__dict__,
            sort_keys=False,
            indent=4)
         or
        def toJSON(self):
        import json
        d = {('__elements' if k == 'elements' else k): v
                 for k, v in self.__dict__.items()}
        return json.dumps(
            d,
            default=lambda o: o.__dict__,
            sort_keys=False,
            indent=4)

         */
        sb.append(INDENT).append("def toJSON(self):\n");
        sb.append(INDENT).append(INDENT).append("import json\n");
        if (true) { // LUC, TODO, need an annotation to trigger this renaming when serializing, to avoid breaking existing code that relies on the field being named 'elements' in the JSON output
            sb.append(INDENT).append(INDENT).append("d = {('__elements' if k == 'elements' else k): v\n");
            sb.append(INDENT).append(INDENT).append(INDENT).append("for k, v in self.__dict__.items()}\n");
        }
        sb.append(INDENT).append(INDENT).append("return json.dumps(\n");
        if (true) { // LUC, same TODO
            sb.append(INDENT).append(INDENT).append(INDENT).append("d,\n");
        } else {
            sb.append(INDENT).append(INDENT).append(INDENT).append("self,\n");
        }
        sb.append(INDENT).append(INDENT).append(INDENT).append("default=lambda o: o.__dict__,\n");
        sb.append(INDENT).append(INDENT).append(INDENT).append("sort_keys=False,\n");
        sb.append(INDENT).append(INDENT).append(INDENT).append("indent=4)\n\n");


    }

    private void emitStaticFields(List<Field> fields) {
        for (Field field : fields) {
            boolean isClassInitialised=false;
            if (!field.annotation.isEmpty()) {
                for (PastAnnotation annot : field.annotation) {
                    if (annot instanceof PythonAnnotation) {
                        if (ClassInitialiser.NAME.equals(annot.getName())) {
                            //System.out.println("----------- Not Processing @ClassInitialiser annotation");
                            isClassInitialised=true;
                        }
                    }
                }
            }
            if (!isClassInitialised) {
                String fieldName = sanitizeName(field.name);
                if (field.initialiser!=null) {
                    if (field.modifiers.contains(Modifier.STATIC)) {
                        sb.append(INDENT)
                                .append(fieldName)
                                .append(" = ").append(convert(field.initialiser)).append("\n");
                    }
                } else {
                    sb.append(INDENT)
                            .append(fieldName)
                            .append(" = ").append("None").append("\n");
                }
            }
        }
    }

    private void emitMethod(Method method) {
        // Method docstring
        if (method.comments != null && !method.comments.isEmpty()) {
            sb.append(INDENT).append("\"\"\"");
            sb.append(method.comments.stream().map(this::convert).flatMap(Collection::stream).collect(Collectors.joining("\n" + INDENT)));
            sb.append("\"\"\"\n");
        }
        boolean foundClassMethod=false;
        boolean foundRegisterMethod=false;
        boolean foundSingleDispatchMethod=false;

        if (method.modifiers.contains(Modifier.STATIC)) {
            for(PastAnnotation annot: method.annotation) {
                if (annot instanceof PythonAnnotation) {
                    if (annot.getName().equals(ClassMethod.NAME)) {
                        foundClassMethod=true;
                        sb.append(INDENT).append("@classmethod\n");
                    }
                }
            }
            if (!foundClassMethod) {
                sb.append(INDENT).append("@staticmethod\n");
            }
        }

        //https://www.index.dev/blog/function-overloading-in-python
        for (PastAnnotation annot: method.annotation) {
            if (annot instanceof PythonAnnotation) {
                if (annot.getName().equals(SingleDispatchMethod.NAME)) {
                    foundSingleDispatchMethod=true;
                }
                if (annot.getName().equals(RegisterMethod.NAME)) {
                    foundRegisterMethod=true;

                }
            }
        }

        // Prefer registry-based alt name over singledispatch/register pattern
        String altName = findAltNameForDeclaration(method);

        // DELETE ME
        if (false && altName == null) {
            // Fall back to singledispatch/register pattern from PAST annotations
            if (foundSingleDispatchMethod) {
                sb.append(INDENT).append("# https://stackoverflow.com/questions/24601722/how-can-i-use-functools-singledispatch-with-instance-methods\n")
                        .append(INDENT).append("""
                        def methdispatch(func):
                                dispatcher = singledispatch(func)
                                def wrapper(*args, **kw):
                                    return dispatcher.dispatch(args[1].__class__)(*args, **kw)
                                wrapper.register = dispatcher.register
                                update_wrapper(wrapper, dispatcher)
                                return wrapper

                        """);
                sb.append(INDENT).append("@methdispatch\n");
                sb.append(INDENT).append("def ").append(sanitizeName(method.name)).append("(self,").append(sanitizeName(method.parameters.get(0).name)).append("):\n");
                sb.append(INDENT).append(INDENT).append("pass\n\n");
                imports.add("functools.singledispatch");
            }

            if (foundRegisterMethod) {
                TypeName inClazz= method.parameters.get(0).type;
                String inTypeName=importAndGetLocalName(sanitizeName(convert(inClazz)));
                sb.append(INDENT).append("@").append(method.name).append(".register(").append(inTypeName).append(")\n");
            }
        }

        // Method signature
        String methodName=method.name;
        if (altName != null) {
            methodName = altName; // use registry-derived alt name for overloaded method
        } else if (foundRegisterMethod) {
            methodName="_"; // https://www.index.dev/blog/function-overloading-in-python
        }
        sb.append(INDENT).append("def ").append(sanitizeName(methodName));
        sb.append("(");
        boolean first=false;
        if (method.modifiers.contains(Modifier.STATIC)) {
            if (foundClassMethod) {
                sb.append("cls");
                first=true;
            }
            // for @static methods, no self parameter
        } else {
            sb.append("self");
            first=true;
        }

        // Parameters
        if (method.parameters != null) {
            for (var param : method.parameters) {
                if (!first) {
                    first=true;
                } else {
                    sb.append(", ");
                }
                sb.append(sanitizeName(param.name));
            }
        }
        sb.append("):\n");

        // Method body placeholder

        method.body.forEach(statement -> {
            // Here we would convert each statement to Python code
            // For now, we just add a placeholder comment
            emitStatement (statement, INDENT + INDENT);
        });
        sb.append(INDENT).append(INDENT).append("pass\n\n");


    }

    /**
     * Look up the alt name for a method declaration from the TypeRegistry.
     * Returns null if no overloaded alt name is registered for this method.
     */
    private String findAltNameForDeclaration(Method method) {
        if (currentClassSignature == null || typeRegistry == null) return null;
        int paramCount = method.parameters == null ? 0 : method.parameters.size();
        for (MethodSignature ms : currentClassSignature.methods) {
            if (!ms.name.equals(method.name)) continue;
            if (ms.parameterTypes.size() != paramCount) continue;
            for (PastAnnotation ann : ms.getAnnotations()) {
                if (ann instanceof OverloadedMethod) {
                    if (paramCount == 0 || paramTypesMatch(method, ms)) {
                        return ((OverloadedMethod) ann).getAltName();
                    }
                }
            }
        }
        return null;
    }

    /**
     * Look up the alt name for a self-method call site from the TypeRegistry.
     * Returns non-null only when there is exactly one overloaded candidate with the given arg count,
     * to avoid ambiguous resolution.
     */
    private String findAltNameForCall_argcount(String methodName, int argCount) {
        if (currentClassSignature == null || typeRegistry == null) return null;
        List<MethodSignature> candidates = new ArrayList<>();
        for (MethodSignature ms : currentClassSignature.methods) {
            if (!ms.name.equals(methodName)) continue;
            if (ms.parameterTypes.size() != argCount) continue;
            for (PastAnnotation ann : ms.getAnnotations()) {
                if (ann instanceof OverloadedMethod) {
                    candidates.add(ms);
                    break;
                }
            }
        }
        if (candidates.size() == 1) {
            for (PastAnnotation ann : candidates.get(0).getAnnotations()) {
                if (ann instanceof OverloadedMethod) return ((OverloadedMethod) ann).getAltName();
            }
        }
        return null;
    }

    /**
     * Look up the alt name for a self-method call site using explicit argument types.
     * Unlike {@link #findAltNameForCall_argcount}, this performs exact type matching so it correctly
     * resolves overloads that share the same argument count but differ in parameter types.
     * Note: uses exact type (no subtyping here).
     */
    private String findAltNameForCall(String methodName, List<TypeName> argTypes) {
        if (currentClassSignature == null || typeRegistry == null) return null;
        for (MethodSignature ms : currentClassSignature.methods) {
            if (!ms.name.equals(methodName)) continue;
            if (!paramTypesMatch(argTypes, ms)) continue;
            for (PastAnnotation ann : ms.getAnnotations()) {
                if (ann instanceof OverloadedMethod) return ((OverloadedMethod) ann).getAltName();
            }
        }
        return null;
    }



    private String findAltNameForCall(ClassName className,String methodName, List<TypeName> argTypes) {
        if (typeRegistry==null) return null;
        ClassSignature sig=typeRegistry.lookup(className.simpleName, className.packge);
        if (sig == null) return null;
        for (MethodSignature ms : sig.methods) {
            if (!ms.name.equals(methodName)) continue;
            if (!paramTypesMatch(argTypes, ms)) continue;
            for (PastAnnotation ann : ms.getAnnotations()) {
                if (ann instanceof OverloadedMethod) return ((OverloadedMethod) ann).getAltName();
            }
        }
        return null;
    }





    /**
     * Check whether the parameter types of a PAST Method match those of a registry MethodSignature.
     */
    private boolean paramTypesMatch(Method method, MethodSignature ms) {
        if (method.parameters.size() != ms.parameterTypes.size()) return false;
        List<TypeName> argTypes = new ArrayList<>();
        for (Parameter p : method.parameters) argTypes.add(p.type);
        return paramTypesMatch(argTypes, ms);
    }

    /**
     * Check whether a list of argument types matches the parameter types of a registry MethodSignature.
     */
    private boolean paramTypesMatch(List<TypeName> argTypes, MethodSignature ms) {
        if (argTypes.size() != ms.parameterTypes.size()) return false;
        for (int i = 0; i < argTypes.size(); i++) {
            String argTypeName = typeSimpleName(argTypes.get(i)).toLowerCase();
            String regTypeName = typeSimpleName(ms.parameterTypes.get(i)).toLowerCase();
            if (!argTypeName.equals(regTypeName)) return false;
        }
        return true;
    }

    private static String typeSimpleName(TypeName type) {
        if (type instanceof ClassName) return ((ClassName) type).simpleName;
        if (type instanceof ParameterizedType) return ((ParameterizedType) type).getRawType().simpleName;
        if (type instanceof ArrayType) return typeSimpleName(((ArrayType) type).elementType) + "Array";
        if (type instanceof TypeVariable) return ((TypeVariable) type).name;
        return type.toString();
    }

    String postDecrement=null;

    private void emitStatement(Statement statement, String indent) {
        switch (statement.statementKind) {
            case ASSIGNMENT -> {

                Assignment assignment = (Assignment) statement;
                if (!assignment.annotation.isEmpty()) {
                    for (String annot : assignment.annotation) {
                        if (annot.startsWith("@import")) {
                            // get the string following @import
                            String importString = annot.substring(7).trim();
                            delayedImport(sb, indent, importString);

                        }
                    }
                }
                if (assignment.leftHandExpression instanceof Variable
                        && ((Variable)assignment.leftHandExpression).name.equals("self")) {
                    return;
                }
                sb.append(indent)
                        .append(sanitizeName(convertLH(assignment.leftHandExpression)))
                        .append(" = ")
                        .append(sanitizeName(convert(assignment.value)))
                        .append("\n");

                if (postDecrement!=null) {
                    sb.append(indent)
                            .append(postDecrement)
                            .append(" -= 1")
                            .append("\n");
                    postDecrement=null;
                }

            }


            case DEFINITION -> {

                Definition definition = (Definition) statement;
                if (!definition.annotation.isEmpty()) {
                    for (String annot : definition.annotation) {
                        if (annot.startsWith("@import")) {
                            // get the string following @import
                            String importString = annot.substring(7).trim();
                            delayedImport(sb, indent, importString);

                        }
                    }
                }
                if (definition.leftHandExpression instanceof Variable
                        && ((Variable)definition.leftHandExpression).name.equals("self")) {
                    return;
                }
                sb.append(indent)
                        .append(sanitizeName(convertLH(definition.leftHandExpression)))
                        .append(" = ")
                        .append(sanitizeName(convert(definition.value)))
                        .append("\n");

                if (postDecrement!=null) {
                    sb.append(indent)
                            .append(postDecrement)
                            .append(" -= 1")
                            .append("\n");
                    postDecrement=null;
                }

            }

            case RETURN -> {
                Return ret = (Return) statement;
                sb.append(indent)
                        .append("return ")
                        .append(sanitizeName(convert(ret.expression)))
                        .append("\n");

            }
            case COMMENT -> {
                Comment cs = (Comment) statement;
                sb.append(indent)
                        .append("# ")
                        .append(convert(cs).stream().map(line -> line.replace("\n", "\n" + indent + "# ")).collect(Collectors.joining("\n")))
                        .append("\n");
            }
            case EXPRESSION_STATEMENT -> {
                Expression es = (Expression) statement;
                sb.append(indent)
                        .append(sanitizeName(convert(es)))
                        .append("\n");
            }
            case IF_STATEMENT -> {
                IfStatement ifs = (IfStatement) statement;
                sb.append(indent)
                        .append("if ")
                        .append(convert(ifs.condition))
                        .append(":\n");
                if (ifs.thenBlock.isEmpty()) {
                    sb.append(indent).append(INDENT).append("pass\n");
                } else {
                    for (Statement thenStmt : ifs.thenBlock) {
                        emitStatement(thenStmt, indent + INDENT);
                    }
                }
                if (!ifs.elseBlock.isEmpty()) {
                    sb.append(indent)
                            .append("else:\n");
                    for (Statement elseStmt : ifs.elseBlock) {
                        emitStatement(elseStmt, indent + INDENT);
                    }
                }
            }

            case FOR_LOOP -> {
                ForLoop forLoop = (ForLoop) statement;
                Statement initialization = forLoop.initialization;
                Expression condition = forLoop.condition;
                Statement update = forLoop.update;
                emitStatement(initialization, INDENT+INDENT);
                sb.append(indent)
                        .append("while (")
                        .append(convert(condition))
                        .append("):\n");
                for (Statement bodyStmt : forLoop.body) {
                    emitStatement(bodyStmt, indent + INDENT);
                }
                emitStatement(update, indent + INDENT);
            }

            case DO_LOOP -> {
                DoLoop doLoop = (DoLoop) statement;
                sb.append(indent)
                        .append("while True:\n");
                for (Statement bodyStmt : doLoop.body) {
                    emitStatement(bodyStmt, indent + INDENT);
                }
                sb.append(indent).append(INDENT)
                        .append("if not (")
                        .append(convert(doLoop.condition))
                        .append("):\n");
                sb.append(indent).append(INDENT).append(INDENT)
                        .append("break\n");
            }

            case ITERATOR -> {
                Iterator iterator = (Iterator) statement;
                sb.append(indent)
                        .append("for ")
                        .append(sanitizeName(iterator.parameter.name))
                        .append(" in ")
                        .append(convert(iterator.collection))
                        .append(":\n");
                for (Statement bodyStmt : iterator.body) {
                    emitStatement(bodyStmt, indent + INDENT);
                }
            }

            case THROW -> {
                ThrowStatement throwStmt = (ThrowStatement) statement;
                sb.append(indent)
                        .append("raise ")
                        .append(convert(throwStmt.expression))
                        .append("\n");
            }

            case SUPER_CONSTRUCTOR_CALL -> {
                SuperConstructorCall superCall = (SuperConstructorCall) statement;
                sb.append(indent)
                        .append("super().__init__(")
                        .append(superCall.arguments.stream().map(this::convert).collect(Collectors.joining(", ")))
                        .append(")\n");
            }

            default -> {
                throw new IllegalArgumentException("Unsupported statement type " + statement);
            }
        }
    }

    private String convertStatementForLambda(Statement statement, String indent) {
        StringBuilder sb=new StringBuilder();
        switch (statement.statementKind) {
            case ASSIGNMENT -> {
                Assignment assignment = (Assignment) statement;
                sb.append(indent)
                        .append(sanitizeName(convertLH(assignment.leftHandExpression)))
                        .append(" = ")
                        .append(sanitizeName(convert(assignment.value)));
            }
            case EXPRESSION_STATEMENT -> {
                Expression es = (Expression) statement;
                switch (es.expressionKind) {
                    case METHOD_CALL -> {
                        MethodCall mc=(MethodCall) es;
                        sb.append(indent).append(convertMethodCall(mc));
                    }
                    case ARRAY_INITIALISER -> {
                        ArrayInitialiser ai = (ArrayInitialiser) statement;
                        sb.append(indent).append(convert(ai));
                    }

                    default -> {
                        throw new UnsupportedOperationException("Lambda body restriction: Unsupported EXPRESSION_STATEMENT kind " + es.expressionKind);
                    }
                }
            }
            case RETURN -> {
                Return ret = (Return) statement;
                sb.append(indent)
                        .append(sanitizeName(convert(ret.expression)));
            }

            default -> {
                throw new IllegalArgumentException("Unsupported statement type " + statement);
            }
        }
        return sb.toString();
    }

    private String convert(Expression expression) {
        switch (expression.expressionKind) {
            case VARIABLE: {
                Variable ve = (Variable) expression;
                return switch (ve.field) {
                    case STATIC_FIELD_VARIABLE -> "cls." + sanitizeName(ve.name);
                    case FIELD_VARIABLE -> "self." + sanitizeName(ve.name);
                    case LOCAL_VARIABLE -> convertVariableName(sanitizeName(ve.name));
                };
            }
            case CONSTANT: {
                Constant constant = (Constant) expression;
                return convertConstant(constant);
            }
            case METHOD_CALL: {
                MethodCall mc = (MethodCall) expression;
                return convertMethodCall(mc);
            }
            case ARRAY_INITIALISER: {
                ArrayInitialiser ai = (ArrayInitialiser) expression;
                StringBuilder result = new StringBuilder();
                result.append("[");
                result.append(ai.values.stream()
                        .map(this::convert)
                        .map(this::sanitizeName)
                        .collect(Collectors.joining(", ")));
                result.append("]");
                return result.toString();
            }
            case CAST: {
                CastExpression c = (CastExpression) expression;
                // ignore type in Python
                return convert(c.expression);
            }
            case LAMBDA_EXPRESSION: {
                LambdaExpression le = (LambdaExpression) expression;
                if (le.body.size() != 1) {
                    String funName="funLambda" + (lambdaCount++);
                    Method method=new Method(funName);
                    method.parameters.addAll(le.parameters.stream().map(p -> new Parameter(sanitizeName(p.name), p.type)).collect(Collectors.toList()));
                    method.body.addAll(le.body);
                    
                    lateEmitMethod(method);

                    LambdaExpression le2=new LambdaExpression(le.parameters);
                    le2.body.add(
                            new MethodCall("self."+funName, le.parameters.stream().map(p -> new Variable(p.name)).collect(Collectors.toList())));

                   le=le2;
                }
                StringBuilder result = new StringBuilder();
                result.append("lambda ");
                result.append(le.parameters.stream()
                        .map(p -> sanitizeName(p.name))
                        .collect(Collectors.joining(", ")));
                result.append(": ");
                if (le.body.size() != 1) {
                    throw new IllegalArgumentException("Only single-expression lambdas are supported in this emitter");
                }
                result.append(convertStatementForLambda(le.body.get(0), INDENT));
                return result.toString();
            }
            case POST_INCREMENT: {
                PostIncrement pi = (PostIncrement) expression;
                Expression expre = pi.expression;
                if (pi.increment<0) {
                    postDecrement=convert(expre);
                    return convert(expre);
                } else {
                    return convert(expre) + "++";
                }
            }
            case ARRAY_ACCESSOR: {
                ArrayAccessor aa = (ArrayAccessor) expression;
                return convert(aa.arrayExpression) + "[" + convert(aa.indexExpression) + "]";
            }
            case BINARY_OP: {
                BinaryOp bo = (BinaryOp) expression;
                if (bo.op.equals(INSTANCEOF)) {
                    throw new IllegalArgumentException("Unexpected use of instanceof operator in binary operation. Use the dedicated INSTANCEOF expression kind instead.");
                } else {
                    return convert(bo.left) + " " + convertOp(bo.op) + " " + convert(bo.right);
                }
            }

            case INSTANCEOF: {
                InstanceOf io = (InstanceOf) expression;
                String typeName = convertForInstanceCheck(io.type);
                return "isinstance(" + convert(io.expression) + ", " + importAndGetLocalName(sanitizeName(typeName)) + ")";
            }

            case IF_EXPRESSION: {
                IfExpression ie = (IfExpression) expression;
                return convert(ie.thenExpression) + " if " + convert(ie.condition) + " else " + convert(ie.elseExpression);
            }

            case ARRAY_ALLOCATOR: {
                ArrayAllocator aa = (ArrayAllocator) expression;
                StringBuilder result = new StringBuilder();
                result.append("[None] * (");
                result.append(convert(aa.size));
                result.append(")");
                return result.toString();
            }

            default:
               throw new IllegalArgumentException("Unsupported expression type " + expression);
        }
    }

    private String convertOp(String op) {
        return switch (op) {
            case "&&" -> "and";
            case "||" -> "or";
            case "!" -> "not ";
            case "Objects.equals" -> "==";
            default -> op;
        };
    }

    private String convertVariableName(String name) {
        if (name.equals("this")) {
            return "self";
        } else if (name.equals("throw")) {
            return "raise";
        } else {
            return name;
        }
    }


    private String convertConstant(Constant c) {
        return switch (c.constantType) {
            case STRING -> (c.value.toString().contains("\""))? "'" + c.value.toString() + "'" : "\"" + c.value.toString() + "\"";
            case INTEGER -> c.value.toString();
            case LONG -> c.value.toString();
            case FLOAT -> c.value.toString();
            case DOUBLE -> c.value.toString();
            case BOOLEAN -> c.value.toString();
            case NULL -> "0";
            case BOOL -> capitalise(c.value.toString());
        };
    }

    private String capitalise(String input) {
        if (input == null || input.isEmpty()) {
            return input;
        }
        return input.substring(0, 1).toUpperCase() + input.substring(1);
    }

    private String convertMethodCall(MethodCall mc) {
        StringBuilder result= new StringBuilder();
        switch(mc.operatorKind) {
            case CONSTRUCTOR_CALL -> {
                if (mc.clazz!=null) {
                    return emitAnonymous(mc.clazz) ;
                }
                assert mc.className!=null;
                if (isMap(mc.className)) {
                    return "Map()";
                }
                if (isList(mc.className)) {
                    return "List()";
                }
                result.append(importAndGetLocalName(sanitizeName(convert(mc.className)))).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .map(this::sanitizeName)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }
            case OBJECT_METHOD_CALL -> {
                assert mc.object!=null;
                String convertedObject = convert(mc.object);
                String callMethodName = updateMethodNameIfOverloaded(mc, convertedObject, sanitizeName(mc.methodName));

                result.append(convertedObject).append(".").append(callMethodName).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .map(this::sanitizeName)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }
            case OBJECT_ACCESSOR -> {
                if (mc.className != null) {
                    //                    return CodeBlock.of("$T.$L", convert(methodCall.className), methodCall.methodName);
                    result.append(importAndGetLocalName(sanitizeName(convert(mc.className)))).append(".").append(sanitizeName(mc.methodName));
                } else  if (mc.object instanceof Variable) {
                    result.append(convert(mc.object)).append(".").append(sanitizeName(mc.methodName));
                } else if (mc.object instanceof MethodCall) {
                    MethodCall mc2 = (MethodCall) mc.object;
                    result.append(convert(mc2)).append(".").append(mc.methodName);
                }else {
                    throw new IllegalArgumentException("Unsupported object type in accessor: " + mc.object);
                }
                return result.toString();
            }

            case FUNCTIONAL_INTERFACE_CALL, OPERATOR_VARIABLE -> {
                assert mc.object!=null;
                assert mc.methodName!=null;
                if (mc.methodName.equals("forEach")) {
                  return convertListForEach(mc);
                }
                if (mc.operatorKind.equals(FUNCTIONAL_INTERFACE_CALL)) {
                    // methodName is a method of a functional interface. In python, the function is called directly instead, without naming a method
                    result.append(convert(mc.object)).append("(");
                } else {
                    String convertedObject = convert(mc.object);
                    String callMethodName = updateMethodNameIfOverloaded(mc, convertedObject, sanitizeName(mc.methodName));
                    result.append(convertedObject).append(".").append(callMethodName).append("(");
                }
                if (mc.arguments != null) {

                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .map(this::sanitizeName)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }
            case SUPER_METHOD_CALL -> {
                assert mc.methodName!=null;
                result.append("super().").append(sanitizeName(mc.methodName)).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .map(this::sanitizeName)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }
            case STATIC_METHOD_CALL -> {
                assert mc.className!=null;
                result.append(importAndGetLocalName(sanitizeName(convert(mc.className)))).append(".").append(sanitizeName(mc.methodName)).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .map(this::sanitizeName)

                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }
            case NO_OPERATOR -> {

                String str = sanitizeName(mc.methodName);
                if (str.equals("getMap")) {
                    str="self.outer.getMap"; // this a hack to deal with anonymous class;
                    // Ideally, we should add an annotation to drive the behaviour of the emitter instead of hardcoding this logic here
                }
                result.append(str).append("(");
                if (mc.arguments != null) {
                    result.append(mc.arguments.stream()
                            .map(this::convert)
                            .map(this::sanitizeName)
                            .collect(Collectors.joining(", ")));
                }
                result.append(")");
                return result.toString();
            }

        }
        throw new IllegalArgumentException("Unsupported method call type " + mc);

    }

    int anonymousClassCount=0;

    private String emitAnonymous(Class clazz) {
        // create an internal class, and create an instance
        String intf=clazz.interfaces.isEmpty() ? "Nointerface" : ((ClassName)clazz.interfaces.get(0)).simpleName;
        String className="Anonymous" + intf + (anonymousClassCount++);
        ClassName outer=new ClassName(currentClassName, currentPackageName);
        lateEmittedClasses.add(new LateEmittedClass(className, clazz, outer));
        return className + "(self)";
    }

    List<LateEmittedClass> lateEmittedClasses=new ArrayList<>();

    static class LateEmittedClass extends Class {
        Class clazz;

        public LateEmittedClass(String className, Class clazz, TypeName outer) {
            super(className);
            this.clazz = clazz;
            this.comments.addAll(clazz.comments);
            constructors.add(
                    new Constructor()
                            .MODIFIERS(Modifier.PUBLIC)
                            .PARAMETER(outer, "outer")
                            .BODY(ASSIGNMENT( METHOD_CALL(VARIABLE("this"),"outer"), VARIABLE( "outer"))));

            methods.addAll(clazz.methods);
            interfaces.addAll(clazz.interfaces);
            typeVariables.addAll(clazz.typeVariables);
            modifiers.addAll(clazz.modifiers);
        }
    }

    private String updateMethodNameIfOverloaded(MethodCall mc, String convertedObject, String callMethodName) {
        if ("self".equals(convertedObject) || (mc.object.inferredType instanceof ClassName)) {
            int argCount = mc.arguments == null ? 0 : mc.arguments.size();
            if (argCount!=0) {
                List<TypeName> argumentTypes= mc.arguments.stream().map(a -> a.inferredType).collect(Collectors.toList());
                String resolvedAlt;
                if ("self".equals(convertedObject)) {
                    resolvedAlt=findAltNameForCall(mc.methodName, argumentTypes);
                } else {
                    resolvedAlt=findAltNameForCall((ClassName) mc.object.inferredType, callMethodName, argumentTypes);
                }
                if (resolvedAlt != null) {
                    callMethodName = sanitizeName(resolvedAlt);
                }
            }
        }
        return callMethodName;
    }

    private boolean isMap(TypeName typeName) {
        switch (typeName.typeKind) {
            case CLASS:
                ClassName cn = (ClassName) typeName;
                String fullName = (cn.packge != null && !cn.packge.isEmpty()) ? (cn.packge + "." + cn.simpleName) : cn.simpleName;
                return fullName.equals("past.util.Map") || fullName.equals("past.util.HashMap");
            case PARAMETERIZED:
                ParameterizedType pt = (ParameterizedType) typeName;
                return isMap(pt.rawType);
            default:
                return false;
        }
    }
    private boolean isList(TypeName typeName) {
        switch (typeName.typeKind) {
            case CLASS:
                ClassName cn = (ClassName) typeName;
                String fullName = (cn.packge != null && !cn.packge.isEmpty()) ? (cn.packge + "." + cn.simpleName) : cn.simpleName;
                return fullName.equals("past.util.List") || fullName.equals("past.util.LinkedList")|| fullName.equals("past.util.ArrayList");
            case PARAMETERIZED:
                ParameterizedType pt = (ParameterizedType) typeName;
                return isList(pt.rawType);
            default:
                return false;
        }
    }

    private String convertListForEach(MethodCall mc) {
        Expression expression = mc.arguments.get(0);
        LambdaExpression le = (LambdaExpression) expression;
        StringBuilder sb=new StringBuilder();
        sb.append("for ").append(sanitizeName(le.parameters.get(0).name)).append(" in ").append(convert(mc.object)).append(":\n");
        for (Statement stmt: le.body) {
            sb.append(convertStatementForLambda(stmt,INDENT + INDENT + INDENT));
            sb.append("\n");
            if (postDecrement!=null) {
                sb.append(INDENT + INDENT + INDENT)
                        .append(postDecrement)
                        .append(" -= 1")
                        .append("\n");
                postDecrement=null;
                sb.append("\n");
            }
        }
        return sb.toString();
    }

    private String convertLH(Expression leftHandExpression) {

        if (leftHandExpression instanceof Variable) {
            Variable ve = (Variable) leftHandExpression;
            return ve.name;
        } else if (leftHandExpression instanceof MethodCall) {
            MethodCall mc = (MethodCall) leftHandExpression;
            return convertMethodCall(mc);
        } else if (leftHandExpression instanceof ArrayAccessor) {
            ArrayAccessor aa = (ArrayAccessor) leftHandExpression;
            return convert(aa.arrayExpression) + "[" + convert(aa.indexExpression) + "]";
        }
        throw new IllegalArgumentException("Unsupported left-hand expression type");
    }


    private boolean isStaticOrFinal(Field field) {
        return field.modifiers.contains(Modifier.STATIC) ||
                field.modifiers.contains(Modifier.FINAL);
    }

    public String getConverterForDeclaredType2(java.lang.Class cl) {
        if (cl != null) {
            String keyType = cl.getName();
            switch (keyType) {
                case "java.lang.Integer":
                    return "Integer.valueOf";
                case "java.lang.Long":
                    return "Long.valueOf";
                case "java.lang.String":
                    return null;
                case "java.lang.Boolean":
                    return "Boolean.valueOf";
                case "java.lang.Float":
                    return "Float.valueOf";
                case "java.lang.Double":
                    return "Double.valueOf";
                default:
                    throw new UnsupportedOperationException();
            }
        } else {
            return null;
        }
    }

    Map<String, String> functionNameConversion = new HashMap<>() {{
        put("Integer.valueOf", "int");
        put("Long.valueOf", "int");
        put("Float.valueOf", "float");
        put("Double.valueOf", "float");
        put("Boolean.valueOf", "bool");
        put("add", "append");
        put("class", "__name__");
    }};

    private String sanitizeName(String name) {
        if (name == null) return "unknown";
        if (functionNameConversion.containsKey(name)) {
            return functionNameConversion.get(name);
        }
        if (name.startsWith(GENERATED_VAR_PREFIX)) {
            return name.substring(2);
        }
        // Convert Java naming to Python (camelCase to snake_case)
        //String result = name.replaceAll("([a-z])([A-Z])", "$1_$2").toLowerCase();
        String result=name;
        // Handle reserved keywords
        if (isPythonKeyword(result)) {
            result = result + "_";
        }
        return result;
    }

    private boolean isPythonKeyword(String name) {
        return List.of("and", "as", "assert", "break", "class", "continue",
                        "def", "del", "elif", "else", "except", "finally",
                        "for", "from", "global", "if", "import", "in",
                        "is", "lambda", "nonlocal", "not", "or", "pass",
                        "raise", "return", "try", "while", "with", "yield")
                .contains(name);
    }

    private void delayedImport(StringBuilder sb, String indent, String imprt) {
        String suffix = getLocalName(imprt);
        sb.append(indent).append("from ").append(imprt).append(" import ").append(suffix).append("\n");
    }

}
