

fix:
	cp target.bak/js/com/google/gson/Gson.js target/js/com/google/gson/Gson.js
	cp target.bak/js/com/google/gson/JsonElement.js target/js/com/google/gson/JsonElement.js
	cp target.bak/js/com/google/gson/JsonObject.js target/js/com/google/gson/JsonObject.js

	cp target.bak/js/org/openprovenance/apache/commons/lang/builder/EqualsBuilder.js  target/js/org/openprovenance/apache/commons/lang/builder/EqualsBuilder.js
	cp target.bak/js/org/openprovenance/apache/commons/lang/builder/EqualsBuilder.js target/js/org/openprovenance/apache/commons/lang/builder/EqualsBuilder.js

	cp target.bak/js/org/openprovenance/prov/json/ProvDocumentDeserializer.js target/js/org/openprovenance/prov/json/ProvDocumentDeserializer.js
	cp target.bak/js/org/openprovenance/prov/json/ProvDocumentSerializer.js target/js/org/openprovenance/prov/json/ProvDocumentSerializer.js

	cp target.bak/js/org/openprovenance/prov/model/Namespace.js target/js/org/openprovenance/prov/model/Namespace.js
	cp target.bak/js/org/openprovenance/prov/model/ProvFactory.js target/js/org/openprovenance/prov/model/ProvFactory.js
	cp target.bak/js/org/openprovenance/prov/model/ValueConverter.js target/js/org/openprovenance/prov/model/ValueConverter.js

#	cp target.bak/js/org/openprovenance/prov/vanilla/Entity.js target/js/org/openprovenance/prov/vanilla/Entity.js



