
do:
	export XJC_OPTS="-Dxml.catalog.verbosity=999";	xjc -b src/main/resources/bindings.xjb -catalog src/main/resources/catalog.cat  src/main/resources/validation.xsd src/main/resources/collection.xsd  src/main/resources/prov-20120920.xsd 
