package org.openprovenance.prov.service.commonbean.composite;

import org.openprovenance.prov.template.library.plead.client.integrator.*;

public class BeanEnactor2Composite<RESULT> extends BeanEnactor2<RESULT> {
    private final EnactorImplementation<RESULT> realiser;
    private final InputProcessor checker;

    public BeanEnactor2Composite(EnactorImplementation<RESULT> realiser, InputProcessor checker) {
        super(realiser, checker);
        this.realiser = realiser;
        this.checker = checker;
    }
    public Plead_transforming_compositeOutputs process(Plead_transforming_compositeInputs bean) {
        // Generated by class org.openprovenance.prov.template.compiler.CompilerBeanEnactor2, method generateBeanEnactor2
        // in file CompilerBeanEnactor2.java, at line 107
        System.out.println("BeanEnactor2Composite.process  with Extra");
        return realiser.generic_enact(new Plead_transforming_compositeOutputs(),bean,
                b -> checker.process(b),
                (sb,b) -> new QueryInvoker2Composite(sb).process(b),
                (rs,b) -> realiser.beanCompleterFactory(rs,new Object[1]).process(b));
    }
}
